### ISSUE TITLE
怎么设置tag啊 - - 

### ISSUE THREAD

**Issue by LxzBUG** [Petterpx/FloatingX#105]
ScopeHelper.builder()
            .setLayoutView(callPopView)
            .build()
            .toControl(this).show()

**Comment by Petterpx** [comment]
局部浮窗不用设置tag，tag是给全局浮窗设置的(FloatingX.xx)


| |
史艺辉
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月3日 17:27 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [Petterpx/FloatingX] 怎么设置tag啊 - - (Issue #105) |

ScopeHelper.builder()
.setLayoutView(callPopView)
.build()
.toControl(this).show()

**Comment by LxzBUG** [comment]
@LxzBUG 我只在在当前activity显示，但是需要在dialogFragment里判断是否正在显示隐藏

**Comment by Petterpx** [comment]
这是业务设计上的事，不过你可以通过持有浮窗的实例进行判断。
如下：
val scopeFx = ScopeHelper.builder()
.setLayoutView(callPopView)
.build()
.toControl(this)

scopeFx.show()



//是否显示
scopeFx.isShow()


| |
史艺辉
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年08月3日 17:35 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [Petterpx/FloatingX] 怎么设置tag啊 - - (Issue #105) |

@LxzBUG 我只在在当前activity显示，但是需要在dialogFragment里判断是否正在显示隐藏
