### ISSUE TITLE
全局悬浮窗内嵌 Rv，在当前 Activity 上方无法显示

### ISSUE THREAD

**Issue by Goooler** [Petterpx/FloatingX#107]
大概代码如下

```kotlin
object EventFloatingWindow {
  private lateinit var rvAdapter: MainSrlRvAdapter

  fun show(activity: Activity) {
    rvAdapter = MainSrlRvAdapter(object : MainSrlRvAdapter.OnEventListener {})
    val binding = FloatingLayoutBinding.inflate(activity.layoutInflater).also {
      it.rvList.adapter = rvAdapter
    }
    FloatingX.install {
      setContext(activity)
      setLayoutView(binding.root)
      enableFx()
    }
  }

  fun setData(data: List<MainCommonVhModel>) {
    rvAdapter.list = data
  }
}
```

~~调用 `show` 可以显示，调用 `setData` 悬浮窗消失~~

**Comment by Petterpx** [comment]
> 大概代码如下
> 
> ```kotlin
> object EventFloatingWindow {
>   private lateinit var rvAdapter: MainSrlRvAdapter
> 
>   fun show(activity: Activity) {
>     rvAdapter = MainSrlRvAdapter(object : MainSrlRvAdapter.OnEventListener {})
>     val binding = FloatingLayoutBinding.inflate(activity.layoutInflater).also {
>       it.rvList.adapter = rvAdapter
>     }
>     FloatingX.install {
>       setContext(activity)
>       setLayoutView(binding.root)
>       enableFx()
>     }
>   }
> 
>   fun setData(data: List<MainCommonVhModel>) {
>     rvAdapter.list = data
>   }
> }
> ```
> 
> 调用 `show` 可以显示，调用 `setData` 悬浮窗消失

好的，我晚点排查一下。能说一下你上面的 show(activity)方法 什么时机调用的吗

**Comment by Goooler** [comment]
`show` 在页面初始化的时候调用，`setData` 就是每次数据更新之后了

**Comment by Petterpx** [comment]
> `show` 在页面初始化的时候调用，`setData` 就是每次数据更新之后了

我这边测试没复现，你尝试一下我的分支试试? https://github.com/Petterpx/FloatingX/blob/fx_to_rv_changed_simple/app/src/main/java/com/petterp/floatingx/app/test/SimpleRvActivity.kt

**Comment by Goooler** [comment]
你这个是局部的吧，那确实没问题，我把你的代码改成了全局的，也是不能显示

<img width="1426" alt="image" src="https://github.com/Petterpx/FloatingX/assets/10363352/fb00f54b-176e-45b4-9bbd-aa96bc6df2bd">

**Comment by Goooler** [comment]
我又试了下，`show` 放在 `onCreate` 里面确实没问题，但是如果像你写的这个一样，放在按钮中触发，那么当前 Activity 上不会悬浮出来，直到进入下一个 Activity 才可以，在 https://github.com/Goooler/DemoApp/pull/454 可以复现

**Comment by Petterpx** [comment]
https://github.com/Petterpx/FloatingX/pull/111

**Comment by Goooler** [comment]
感谢!
