### ISSUE TITLE
触摸透传

### ISSUE THREAD

**Issue by CyAndroid** [Petterpx/FloatingX#108]
现在的悬浮窗在的地方， 点击后下面的view 无法做出响应，怎样才能 将点击事件透下去呢

**Comment by Petterpx** [comment]
> 现在的悬浮窗在的地方， 点击后下面的view 无法做出响应，怎样才能 将点击事件透下去呢

不支持透传，因为浮窗本身需要点击焦点，而且支持透传后，浮窗本身也就无法移动。

**Comment by CyAndroid** [comment]
> > 现在的悬浮窗在的地方， 点击后下面的view 无法做出响应，怎样才能 将点击事件透下去呢
> 
> 不支持透传，因为浮窗本身需要点击焦点，而且支持透传后，浮窗本身也就无法移动。

我想做一个可以在任何Activity上显示的一个仅供展示的 通告横幅，所以不需要点击拖动悬浮窗，请问有什么办法吗

**Comment by Petterpx** [comment]
> > > 现在的悬浮窗在的地方， 点击后下面的view 无法做出响应，怎样才能 将点击事件透下去呢
> > 
> > 
> > 不支持透传，因为浮窗本身需要点击焦点，而且支持透传后，浮窗本身也就无法移动。
> 
> 我想做一个可以在任何Activity上显示的一个仅供展示的 通告横幅，所以不需要点击拖动悬浮窗，请问有什么办法吗

周末出一个api支持此功能

**Comment by Petterpx** [comment]
试试1.3.2，已支持此需求，初始化浮窗时调用 setDisplayMode(FxDisplayMode.DisplayOnly) 即可，具体可参照方法简介。
<img width="591" alt="image" src="https://github.com/Petterpx/FloatingX/assets/41142188/72a63916-4d05-4f29-9b66-0c34a177271f">
