### ISSUE TITLE
有没有考虑增加半隐藏功能？

### ISSUE THREAD

**Issue by devonEdison** [Petterpx/FloatingX#114]
有没有考虑增加半隐藏功能？
我知道这问题之前问过了。但是还是挺希望可以增加的。
毕竟这需求太大了阿。一个球浮在那边很挡画面。
手机萤幕都这么小了，能不能像是iphone悬浮求那样变成半透明或半隐藏嵌入萤幕外面呢？

如果可以增加半隐藏功能肯定可以吊打下面那个三千星星的库阿～～～
https://github.com/princekin-f/EasyFloat

**Comment by Petterpx** [comment]
todo功能，暂时没工期去做。@devonEdison

**Comment by devonEdison** [comment]
OK
