### ISSUE TITLE
有没有考虑用 Java 17　来编译

### ISSUE THREAD

**Issue by devonEdison** [Petterpx/FloatingX#115]
1. 可以增加 build 速度
2. 新的 android studio 貌似都用 Java 17.
3. 未来安卓编译肯定也试用 Java 17

**Comment by Petterpx** [comment]
对于开源库而言，需要尽可能兼容更多版本，故这个升级并不在优先范围内，但可以考虑升级至11，至于编译速度方面，其实对于aar而言，差异并不大。

**Comment by devonEdison** [comment]
OK
