### ISSUE TITLE
找不到可以吸附上下方的方法，每次都是吸附左右

### ISSUE THREAD

**Issue by devonEdison** [Petterpx/FloatingX#117]
找不到可以吸附上下方的方法，每次都是吸附左右
查了文件都找不到，是不是不支持？

**Comment by Petterpx** [comment]
> 找不到可以吸附上下方的方法，每次都是吸附左右 查了文件都找不到，是不是不支持？

对的，目前不支持吸附上下，可以加上此功能

**Comment by Petterpx** [comment]
已支持，请使用 1.3.4，初始化浮窗时，调用 setEdgeAdsorbDirection(FxAdsorbDirection.LEFT_OR_RIGHT)
