### ISSUE TITLE
当使用viewpager+fragment，其中一个fragment为h5页面，悬浮窗与veiewpager的滑动会冲突

### ISSUE THREAD

**Issue by PaShuiDeYu** [Petterpx/FloatingX#124]

**Comment by Petterpx** [comment]
能具体说明下场景吗？比如是vp+fragment中用浮窗，浮窗安装在fragment中，还是浮窗里放vp+fragment，具体的冲突是指什么？能录个视频或者gif更好。 @PaShuiDeYu

**Comment by PaShuiDeYu** [comment]
使用局部浮窗，添加在内部为webview的fragment中，上下滑动，点击都没问题，左右滑动会触发viewpager的滑动事件，浮窗添加在未使用webview的fragment中时，一切正常，两个fragment都同一viewpager中

**Comment by Petterpx** [comment]
> 使用局部浮窗，添加在内部为webview的fragment中，上下滑动，点击都没问题，左右滑动会触发viewpager的滑动事件，浮窗添加在未使用webview的fragment中时，一切正常，两个fragment都同一viewpager中

抱歉隔了这么久才回复，这并不是浮窗的bug，你需要自行处理webview与viewpager的滑动冲突问题
