### ISSUE TITLE
show方法没了？

### ISSUE THREAD

**Issue by crazyzjw** [Petterpx/FloatingX#126]
升级版本后，没了show方法
版本： implementation 'io.github.petterpx:floatingx:1.3.5'
看了下源码
<img width="943" alt="image" src="https://github.com/Petterpx/FloatingX/assets/12543049/a3f19b4b-5b09-4744-ac96-143bb7487f34">

**Comment by crazyzjw** [comment]
> > 升级版本后，没了show方法 版本： implementation 'io.github.petterpx:floatingx:1.3.5' 看了下源码 <img alt="image" width="943" src="https://user-images.githubusercontent.com/12543049/278292566-a3f19b4b-5b09-4744-ac96-143bb7487f34.png">
> 
> show()方法在之前版本(1.3.0之前)已经移除了，主要是其并不安全，使用 Floatingx.control().show(activity) 即可
局部的浮窗也可以？

**Comment by Petterpx** [comment]
看一下文档吧。
