### ISSUE TITLE
希望能开放查询所有显示的浮窗的接口

### ISSUE THREAD

**Issue by appdev** [Petterpx/FloatingX#133]
看到代码里有这样的方法， 但是，是内部使用的
```kotlin
@JvmSynthetic
    internal fun getFxList(): Map<String, FxAppControlImpl> = fxs
```
希望能开放该方法

**Comment by Petterpx** [comment]
> 看到代码里有这样的方法， 但是，是内部使用的
> 
> ```kotlin
> @JvmSynthetic
>     internal fun getFxList(): Map<String, FxAppControlImpl> = fxs
> ```
> 
> 希望能开放该方法

ok

**Comment by Petterpx** [comment]
> 看到代码里有这样的方法， 但是，是内部使用的
> 
> ```kotlin
> @JvmSynthetic
>     internal fun getFxList(): Map<String, FxAppControlImpl> = fxs
> ```
> 
> 希望能开放该方法

开放该方法的作用是什么?目前没想到有什么场景有需要

**Comment by appdev** [comment]
比如在做SDK开发的时候：用户传过来的 tag 是123，SDK给tag增加一个前缀。ABC-123，在前台关闭的时候，可以通过通过这个前缀关闭这一组浮窗。具体业务有点类似微信小程序，原生提供悬浮窗功能，小程序最小化的时候需要关闭小程序打开的所有悬浮窗

**Comment by appdev** [comment]
还有这里的代码似乎有点问题：
![image](https://github.com/Petterpx/FloatingX/assets/9107717/0833bea2-8aef-4e4c-804e-b4b0eaadad03)

如果在 `install` 里 指定了  X Y 的坐标，必须设置 FxGravity。否则坐标就会被重置为 0

但是在这个方法里面又会又错误输出：
![image](https://github.com/Petterpx/FloatingX/assets/9107717/5a70a7c0-49e3-46a2-873d-bc383fa780d5)

**Comment by Petterpx** [comment]
> SDK给tag增加一个前缀

你看看你FxGravity有没有手动设置过，这块逻辑马上会重构完。

**Comment by Petterpx** [comment]
> 比如在做SDK开发的时候：用户传过来的 tag 是123，SDK给tag增加一个前缀。ABC-123，在前台关闭的时候，可以通过通过这个前缀关闭这一组浮窗。具体业务有点类似微信小程序，原生提供悬浮窗功能，小程序最小化的时候需要关闭小程序打开的所有悬浮窗

合理，会在下个版本加上。

**Comment by Petterpx** [comment]
> 还有这里的代码似乎有点问题： ![image](https://private-user-images.githubusercontent.com/9107717/298848424-0833bea2-8aef-4e4c-804e-b4b0eaadad03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTIzNTUsIm5iZiI6MTcwNjcxMjA1NSwicGF0aCI6Ii85MTA3NzE3LzI5ODg0ODQyNC0wODMzYmVhMi04YWVmLTRlNGMtODA0ZS1iNGIwZWFhZGFkMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMzFUMTQ0MDU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTFlZTY4MWEyYjIyN2NjNjc2ZmMxYmYxMjNjOWI5OTBmNmVjNmI4OTVjNmQ5MGM1Zjk5ZTMxOTBjYTE5NzQ2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.reY4v93VQnm1HoEkoMf--OCuGpq3gWbAZhqiVEBRu6o)
> 
> 如果在 `install` 里 指定了 X Y 的坐标，必须设置 FxGravity。否则坐标就会被重置为 0
> 
> 但是在这个方法里面又会又错误输出：
> 
> ```kotlin
>     private fun initDefaultXY(): Pair<Float, Float> {
>         // 非辅助定位&&非默认位置,此时x,y不可信
>         if (!helper.enableAssistLocation && !helper.gravity.isDefault()) {
>             helper.fxLog?.e(
>                 "fxView--默认坐标可能初始化异常,如果显示位置异常,请检查您的gravity是否为默认配置，当前gravity:${helper.gravity}。\n" +
>                     "如果您要配置gravity,建议您启用辅助定位setEnableAssistDirection(),此方法将更便于定位。",
>             )
>         }
>         return helper.defaultX to checkDefaultY(helper.defaultY)
>     }
> ```

这里的输出异常，只是提示，不用介意。目的就是给用户一个提示，需要自己设置准确的位置。
