### ISSUE TITLE
应用内浮窗会有内存泄漏

### ISSUE THREAD

**Issue by OneGreenHand-LXH** [Petterpx/FloatingX#140]
仅开启应用内浮窗会存在内存泄漏
具体操作步骤：在B页面开启悬浮，返回A页面

java.util.ArrayList instance
  Leaking: UNKNOWN
  Retaining 300 B in 16 objects
  ↓ ArrayList[11]
             ~~~~
com.petterp.floatingx.imp.app.FxAppLifecycleImp instance
  Leaking: UNKNOWN
  Retaining 213 B in 6 objects
  ↓ FxAppLifecycleImp.helper
                      ~~~~~~
com.petterp.floatingx.assist.helper.FxAppHelper instance
  Leaking: UNKNOWN
  Retaining 544.4 kB in 8765 objects
  context instance of cn.qssmart.tytptt.util.config.MyApp
  ↓ FxBasisHelper.iFxClickListener
                  ~~~~~~~~~~~~~~~~
cn.qssmart.tytptt.ui.setting.SetUpActivity$15 instance
  Leaking: UNKNOWN
  Retaining 544.2 kB in 8758 objects
  Anonymous class implementing android.view.View$OnClickListener
  this$0 instance of cn.qssmart.tytptt.ui.setting.SetUpActivity with mDestroyed = true
  ↓ SetUpActivity$15.this$0
                     ~~~~~~
cn.qssmart.tytptt.ui.setting.SetUpActivity instance
   Leaking: YES (ObjectWatcher was watching this because cn.qssmart.tytptt.ui.setting.SetUpActivity received
   Activity#onDestroy() callback and Activity#mDestroyed is true)
   Retaining 544.2 kB in 8757 objects
   key = cade785e-25e7-4cac-ab5d-db66c7186754
   watchDurationMillis = 51480
   retainedDurationMillis = 46478
   mContext instance of cn.qssmart.tytptt.ui.setting.SetUpActivity with mDestroyed = true
   mApplication instance of cn.qssmart.tytptt.util.config.MyApp
   mBase instance of androidx.appcompat.view.ContextThemeWrapper

**Comment by Petterpx** [comment]
> 仅开启应用内浮窗会存在内存泄漏 具体操作步骤：在B页面开启悬浮，返回A页面
> 
> java.util.ArrayList instance Leaking: UNKNOWN Retaining 300 B in 16 objects ↓ ArrayList[11] ~~~~ com.petterp.floatingx.imp.app.FxAppLifecycleImp instance Leaking: UNKNOWN Retaining 213 B in 6 objects ↓ FxAppLifecycleImp.helper ~~~~~~ com.petterp.floatingx.assist.helper.FxAppHelper instance Leaking: UNKNOWN Retaining 544.4 kB in 8765 objects context instance of cn.qssmart.tytptt.util.config.MyApp ↓ FxBasisHelper.iFxClickListener ~~~~~~~~~~~~~~~~ cn.qssmart.tytptt.ui.setting.SetUpActivity$15 instance Leaking: UNKNOWN Retaining 544.2 kB in 8758 objects Anonymous class implementing android.view.View$OnClickListener this$0 instance of cn.qssmart.tytptt.ui.setting.SetUpActivity with mDestroyed = true ↓ SetUpActivity$15.this$0 ~~~~~~ cn.qssmart.tytptt.ui.setting.SetUpActivity instance Leaking: YES (ObjectWatcher was watching this because cn.qssmart.tytptt.ui.setting.SetUpActivity received Activity#onDestroy() callback and Activity#mDestroyed is true) Retaining 544.2 kB in 8757 objects key = cade785e-25e7-4cac-ab5d-db66c7186754 watchDurationMillis = 51480 retainedDurationMillis = 46478 mContext instance of cn.qssmart.tytptt.ui.setting.SetUpActivity with mDestroyed = true mApplication instance of cn.qssmart.tytptt.util.config.MyApp mBase instance of androidx.appcompat.view.ContextThemeWrapper

能带一下你在Activity中显示浮窗的示例代码吗？
另外，建议将展示浮窗的代码单独封装为一个静态，而不是直接在某Activiry中，避免对象无法回收。

**Comment by OneGreenHand-LXH** [comment]
[
<img width="747" alt="微信图片_20240326191403" src="https://github.com/Petterpx/FloatingX/assets/161918135/955eb2ed-958e-49dc-9e77-eb7969b8230b">
<img width="844" alt="微信图片_20240326191510" src="https://github.com/Petterpx/FloatingX/assets/161918135/791bbaf4-43bb-4b1d-a257-bd3ede65ab98">
](url)

**Comment by OneGreenHand-LXH** [comment]
改写在静态类了，貌似没啥问题了

**Comment by Petterpx** [comment]
> 改写在静态类了，貌似没啥问题了

因为你注册了touchListener,这种匿名内部类的方式导致隐式持有了外部activity,从而内存泄漏
