### ISSUE TITLE
通过 MediaProject 录制屏幕的时候不展示悬浮球应该怎么处理？或者说不把悬浮球录制进去

### ISSUE THREAD

**Issue by 13120241790** [Petterpx/FloatingX#142]
通过 MediaProject 录制屏幕的时候不展示悬浮球应该怎么处理？或者说不把悬浮球录制进去

**Comment by Petterpx** [comment]
> 通过 MediaProject 录制屏幕的时候不展示悬浮球应该怎么处理？或者说不把悬浮球录制进去

问问万能的GPT呢，此问题并不是fx所考虑的呢。
