### ISSUE TITLE
悬浮窗能做到初始状态传递一个自定义View和整个屏幕一样大吗？然后在自定义View中去点击变成小窗模式，再点击还原到全屏悬浮窗

### ISSUE THREAD

**Issue by 13120241790** [Petterpx/FloatingX#143]
悬浮窗能做到初始状态传递一个自定义View和整个屏幕一样大吗？然后在自定义View中去点击变成小窗模式，再点击还原到全屏悬浮窗

现在试验的情况是悬浮窗的初始值必须要给定具体的 px 如果给的是 match_parent 则不会展示

我这样想把悬浮窗

            FloatingX.install {
                setContext(applicationContext)
                setLayoutView(windowView)
                setScopeType(FxScopeType.SYSTEM_AUTO)
            }.show()

FloatingX.control().updateView(fullScreenView(windowView))
更新到全屏大小是没有作用的

    /**
     * 通过 layoutParams 操作试图改变窗体大小
     */
    fun fullScreenView(windowView: RenderSmallWindowView): RenderSmallWindowView {
        val layoutParams = windowView.layoutParams
        layoutParams.width = RTCUtils.getDisplayMetrics(this).widthPixels
        layoutParams.height = RTCUtils.getDisplayMetrics(this).heightPixels
        windowView.layoutParams = layoutParams
        return windowView
    }

**Comment by Petterpx** [comment]
> 悬浮窗能做到初始状态传递一个自定义View和整个屏幕一样大吗？然后在自定义View中去点击变成小窗模式，再点击还原到全屏悬浮窗
> 
> 现在试验的情况是悬浮窗的初始值必须要给定具体的 px 如果给的是 match_parent 则不会展示
> 
> 我这样想把悬浮窗
> 
> ```
>         FloatingX.install {
>             setContext(applicationContext)
>             setLayoutView(windowView)
>             setScopeType(FxScopeType.SYSTEM_AUTO)
>         }.show()
> ```
> 
> FloatingX.control().updateView(fullScreenView(windowView)) 更新到全屏大小是没有作用的
> 
> ```
> /**
>  * 通过 layoutParams 操作试图改变窗体大小
>  */
> fun fullScreenView(windowView: RenderSmallWindowView): RenderSmallWindowView {
>     val layoutParams = windowView.layoutParams
>     layoutParams.width = RTCUtils.getDisplayMetrics(this).widthPixels
>     layoutParams.height = RTCUtils.getDisplayMetrics(this).heightPixels
>     windowView.layoutParams = layoutParams
>     return windowView
> }
> ```

晚点出api支持此功能吧，具体来说需要浮窗容器配合做调整，对于系统浮窗，目前没有api做支持，对于app浮窗，可以使用getManagerView() 同时设置浮窗容器params。 
相应的，对于你现在的需求，你可以考虑获取屏幕大小然后进行设置。

**Comment by 13120241790** [comment]
好的谢谢
