### ISSUE TITLE
两个Activity如果使用了共享元素动画就会出问题

### ISSUE THREAD

**Issue by chinamingsss** [Petterpx/FloatingX#144]
A 和 B 实现了共享元素动画   从A 跳转到 B 这个时候是显示正常  但是当你关闭 B 返回A 的时候 A 就不显示这个悬浮了，就出现问题了

**Comment by Petterpx** [comment]
> A 和 B 实现了共享元素动画 从A 跳转到 B 这个时候是显示正常 但是当你关闭 B 返回A 的时候 A 就不显示这个悬浮了，就出现问题了

目前没有遇到这样的问题，可以考虑将你的示例贴过来吗。
