### ISSUE TITLE
应用进程杀死问题

### ISSUE THREAD

**Issue by HelloJokerWord** [Petterpx/FloatingX#147]
大佬，想问下，能不能给个配置就是，应用进程杀死了，悬浮窗也跟随销毁，
就home键到桌面，然后打开menu键，杀死app，然后现在是悬浮窗还在，想要关闭，有没有配置的方法

**Comment by HelloJokerWord** [comment]
极端情况下遇到个这个。
 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                                                                         	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9995)
                                                                         	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1965)
                                                                         	at android.view.View.requestLayout(View.java:26038)
                                                                         	at android.view.View.setFlags(View.java:16554)
                                                                         	at android.view.View.setVisibility(View.java:11997)
                                                                         	at com.petterp.floatingx.util._FxExt.setVisibility(FxExt.kt:39)
                                                                         	at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.hide(FxSystemPlatformProvider.kt:51)
                                                                         	at com.petterp.floatingx.imp.FxBasisControlImp.hide(FxBasisControlImp.kt:63)

**Comment by Petterpx** [comment]
> 极端情况下遇到个这个。 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9995) at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1965) at android.view.View.requestLayout(View.java:26038) at android.view.View.setFlags(View.java:16554) at android.view.View.setVisibility(View.java:11997) at com.petterp.floatingx.util._FxExt.setVisibility(FxExt.kt:39) at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.hide(FxSystemPlatformProvider.kt:51) at com.petterp.floatingx.imp.FxBasisControlImp.hide(FxBasisControlImp.kt:63)

这明显是你非UI线程调用了 hide()啊，报错很明显。至于第一个问题，进程杀死了，浮窗肯定就没了啊，除非你进程没杀死。基础的问题建议多查查google...

**Comment by HelloJokerWord** [comment]
> > 极端情况下遇到个这个。 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9995) at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1965) at android.view.View.requestLayout(View.java:26038) at android.view.View.setFlags(View.java:16554) at android.view.View.setVisibility(View.java:11997) at com.petterp.floatingx.util._FxExt.setVisibility(FxExt.kt:39) at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.hide(FxSystemPlatformProvider.kt:51) at com.petterp.floatingx.imp.FxBasisControlImp.hide(FxBasisControlImp.kt:63)
> 
> 这明显是你非UI线程调用了 hide()啊，报错很明显。
> 
> 至于第一个问题，进程杀死了，浮窗肯定就没了啊，除非你进程没杀死，很有可能只是你的系统做了其他魔改操作，此时进程并没真正被kill，即划掉并不意味kill掉App。 回到问题的解决方向上，浮窗本身没法去监控进程是否被kill了，虽然理论上可以通过监听Activity存在的个数获得一个不咋靠谱的基准，但这样的操作，我认为悬浮窗本身并不应该去支持。

好的，谢谢了

**Comment by HelloJokerWord** [comment]
> > 极端情况下遇到个这个。 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9995) at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1965) at android.view.View.requestLayout(View.java:26038) at android.view.View.setFlags(View.java:16554) at android.view.View.setVisibility(View.java:11997) at com.petterp.floatingx.util._FxExt.setVisibility(FxExt.kt:39) at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.hide(FxSystemPlatformProvider.kt:51) at com.petterp.floatingx.imp.FxBasisControlImp.hide(FxBasisControlImp.kt:63)
> 
> 这明显是你非UI线程调用了 hide()啊，报错很明显。
> 
> 至于第一个问题，进程杀死了，浮窗肯定就没了啊，除非你进程没杀死，很有可能只是你的系统做了其他魔改操作，此时进程并没真正被kill，即划掉并不意味kill掉App。 回到问题的解决方向上，浮窗本身没法去监控进程是否被kill了，虽然理论上可以通过监听Activity存在的个数获得一个不咋靠谱的基准，但这样的操作，我认为悬浮窗本身并不应该去支持。

第一个问题可能我没表达好。
就是我的步骤：
1、clone源码安装demo
2、然后启动并显示全局悬浮窗，且给予应用外显示权限
3、此时我home键退到手机桌面，悬浮窗显示着

**Comment by Petterpx** [comment]
> > > 极端情况下遇到个这个。 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9995) at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1965) at android.view.View.requestLayout(View.java:26038) at android.view.View.setFlags(View.java:16554) at android.view.View.setVisibility(View.java:11997) at com.petterp.floatingx.util._FxExt.setVisibility(FxExt.kt:39) at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.hide(FxSystemPlatformProvider.kt:51) at com.petterp.floatingx.imp.FxBasisControlImp.hide(FxBasisControlImp.kt:63)
> > 
> > 
> > 这明显是你非UI线程调用了 hide()啊，报错很明显。
> > 至于第一个问题，进程杀死了，浮窗肯定就没了啊，除非你进程没杀死，很有可能只是你的系统做了其他魔改操作，此时进程并没真正被kill，即划掉并不意味kill掉App。 回到问题的解决方向上，浮窗本身没法去监控进程是否被kill了，虽然理论上可以通过监听Activity存在的个数获得一个不咋靠谱的基准，但这样的操作，我认为悬浮窗本身并不应该去支持。
> 
> 第一个问题可能我没表达好。 就是我的步骤： 1、clone源码安装demo 2、然后启动并显示全局悬浮窗，且给予应用外显示权限 3、此时我home键退到手机桌面，悬浮窗显示着 4、然后我menu菜单手动清理掉后台应用。

建议重学Android，这种问题不要再问了

**Comment by HelloJokerWord** [comment]
> > > > 极端情况下遇到个这个。 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9995) at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1965) at android.view.View.requestLayout(View.java:26038) at android.view.View.setFlags(View.java:16554) at android.view.View.setVisibility(View.java:11997) at com.petterp.floatingx.util._FxExt.setVisibility(FxExt.kt:39) at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.hide(FxSystemPlatformProvider.kt:51) at com.petterp.floatingx.imp.FxBasisControlImp.hide(FxBasisControlImp.kt:63)
> > > 
> > > 
> > > 这明显是你非UI线程调用了 hide()啊，报错很明显。
> > > 至于第一个问题，进程杀死了，浮窗肯定就没了啊，除非你进程没杀死，很有可能只是你的系统做了其他魔改操作，此时进程并没真正被kill，即划掉并不意味kill掉App。 回到问题的解决方向上，浮窗本身没法去监控进程是否被kill了，虽然理论上可以通过监听Activity存在的个数获得一个不咋靠谱的基准，但这样的操作，我认为悬浮窗本身并不应该去支持。
> > 
> > 
> > 第一个问题可能我没表达好。 就是我的步骤： 1、clone源码安装demo 2、然后启动并显示全局悬浮窗，且给予应用外显示权限 3、此时我home键退到手机桌面，悬浮窗显示着 4、然后我menu菜单手动清理掉后台应用。
> 
> 进程未kill掉，建议自行排查

是的是的，我的问题，是我以为清掉后台应用就杀掉了，哈哈。

**Comment by Petterpx** [comment]
> > > > > 极端情况下遇到个这个。 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9995) at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1965) at android.view.View.requestLayout(View.java:26038) at android.view.View.setFlags(View.java:16554) at android.view.View.setVisibility(View.java:11997) at com.petterp.floatingx.util._FxExt.setVisibility(FxExt.kt:39) at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.hide(FxSystemPlatformProvider.kt:51) at com.petterp.floatingx.imp.FxBasisControlImp.hide(FxBasisControlImp.kt:63)
> > > > 
> > > > 
> > > > 这明显是你非UI线程调用了 hide()啊，报错很明显。
> > > > 至于第一个问题，进程杀死了，浮窗肯定就没了啊，除非你进程没杀死，很有可能只是你的系统做了其他魔改操作，此时进程并没真正被kill，即划掉并不意味kill掉App。 回到问题的解决方向上，浮窗本身没法去监控进程是否被kill了，虽然理论上可以通过监听Activity存在的个数获得一个不咋靠谱的基准，但这样的操作，我认为悬浮窗本身并不应该去支持。
> > > 
> > > 
> > > 第一个问题可能我没表达好。 就是我的步骤： 1、clone源码安装demo 2、然后启动并显示全局悬浮窗，且给予应用外显示权限 3、此时我home键退到手机桌面，悬浮窗显示着 4、然后我menu菜单手动清理掉后台应用。
> > 
> > 
> > 进程未kill掉，建议自行排查
> 
> 是的是的，我的问题，是我以为清掉后台应用就杀掉了，哈哈。



> > > 极端情况下遇到个这个。 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views. at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:9995) at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1965) at android.view.View.requestLayout(View.java:26038) at android.view.View.setFlags(View.java:16554) at android.view.View.setVisibility(View.java:11997) at com.petterp.floatingx.util._FxExt.setVisibility(FxExt.kt:39) at com.petterp.floatingx.imp.system.FxSystemPlatformProvider.hide(FxSystemPlatformProvider.kt:51) at com.petterp.floatingx.imp.FxBasisControlImp.hide(FxBasisControlImp.kt:63)
> > 
> > 
> > 这明显是你非UI线程调用了 hide()啊，报错很明显。
> > 至于第一个问题，进程杀死了，浮窗肯定就没了啊，除非你进程没杀死，很有可能只是你的系统做了其他魔改操作，此时进程并没真正被kill，即划掉并不意味kill掉App。 回到问题的解决方向上，浮窗本身没法去监控进程是否被kill了，虽然理论上可以通过监听Activity存在的个数获得一个不咋靠谱的基准，但这样的操作，我认为悬浮窗本身并不应该去支持。
> 
> 第一个问题可能我没表达好。 就是我的步骤： 1、clone源码安装demo 2、然后启动并显示全局悬浮窗，且给予应用外显示权限 3、此时我home键退到手机桌面，悬浮窗显示着 4、然后我menu菜单手动清理掉后台应用。
> 
> 然后其实app和你说的一样，其实没有杀死的，悬浮窗还显示着，我目前确实就是监控activity的数量去控制主动关闭悬浮窗了。 就是想着大佬这边有没有更优雅的方式监听上面第四个步骤，然后自动关掉悬浮窗，哈哈

其他方式的话，目前的确没有想到，因为Android没有提供显式的api给开发者通知当前应用已经kill掉。
回到你问题本身，为什么会存在划掉应用，进程没有kill掉，比较奇怪。
