### ISSUE TITLE
系统悬浮窗一闪而过

### ISSUE THREAD

**Issue by HelloJokerWord** [Petterpx/FloatingX#149]
问题描述：设置为系统悬浮窗和默认位置右下角时，特别是一些比较差的手机，会明显在从左上角显示一下，然后快速的滑动到配置的右下角。设置为应用内(FxScopeType.APP) 时，就没这一闪的感觉了，或者好一些

使用版本：2.6.0

测试配置：
 // 设置悬浮窗默认方向
setGravity(FxGravity.RIGHT_OR_CENTER)
 // 设置偏移位置
setOffsetXY(0f, ConvertUtils.dp2px(200f).toFloat())

其他xy什么的就都没设置了。

看了下源码的:
registerWM(wm: WindowManager) 默认  gravity = Gravity.TOP or Gravity.START 
不知道会不会是不是这个原因。

**Comment by Petterpx** [comment]
> registerWM

有一个时机问题，可以考虑后续优化下，目前感知应该几乎很小。
原理是：浮窗要实现各种位置定义时，最好的方式就是自行根据传递的gravity去计算位置，故只能默认先放置在view初始位置(左上角)，后续得到浮窗大小，再进行更新，这里面存在了10ms左右的差值

**Comment by Petterpx** [comment]
更新到2.1.0即可
