### ISSUE TITLE
App级别浮窗在多个Activity之间显示和隐藏会有问题

### ISSUE THREAD

**Issue by gumaola** [Petterpx/FloatingX#150]
Android SDK Version = v2.0.6
具体操作为：
1.启动APP，在Activity A调用FloatingX.install().show()显示一个浮窗。
2.跳转至Activity B，此时浮窗可以正常显示。
3.返回Activity A，调用FloatingX.control(FLOAT_TAG).hide()隐藏浮窗
4.再次跳转至Activity B，此时浮窗也是处于隐藏状态。
**5.然后在Activity B调用FloatingX.control(FLOAT_TAG).show()，这时浮窗无法正常显示，但是返回Activity A时，发现浮窗可以正常显示。**

跟踪源代码发现，错误是发生在这一步：
![image](https://github.com/Petterpx/FloatingX/assets/11657383/7270215b-195e-4b56-8749-9ed2e2c50603)
在Activity B中的containerGroupView依旧是Activity A的DecorView，所以实际是添加在Activity A上显示，而B页面无法及时显示。

**Comment by Petterpx** [comment]
> Android SDK Version = v2.0.6 具体操作为： 1.启动APP，在Activity A调用FloatingX.install().show()显示一个浮窗。 2.跳转至Activity B，此时浮窗可以正常显示。 3.返回Activity A，调用FloatingX.control(FLOAT_TAG).hide()隐藏浮窗 4.再次跳转至Activity B，此时浮窗也是处于隐藏状态。 **5.然后在Activity B调用FloatingX.control(FLOAT_TAG).show()，这时浮窗无法正常显示，但是返回Activity A时，发现浮窗可以正常显示。**
> 
> 跟踪源代码发现，错误是发生在这一步： ![image](https://private-user-images.githubusercontent.com/11657383/323858334-7270215b-195e-4b56-8749-9ed2e2c50603.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTQ3MDUsIm5iZiI6MTcxMzUxNDQwNSwicGF0aCI6Ii8xMTY1NzM4My8zMjM4NTgzMzQtNzI3MDIxNWItMTk1ZS00YjU2LTg3NDktOWVkMmUyYzUwNjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA4MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODg2NjA1NTQ3YmFjYTBmM2FlY2VlNTJhNjY3OWJjMTBhMTRkMWUyYzFkNzY5M2UxOTJhOGM0ZWFmYjdhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SKq0qzYuqIFZesimGP0B8jYLjqmLP5DDh2y9128F0G0) 在Activity B中的containerGroupView依旧是Activity A的DecorView，所以实际是添加在Activity A上显示，而B页面无法及时显示。

B Activity - show()展示时机是onResume之前吗，如果是的话那不行，目前浮窗的插入时机监控是在onResume里做的

**Comment by gumaola** [comment]
> > Android SDK Version = v2.0.6 具体操作为： 1.启动APP，在Activity A调用FloatingX.install().show()显示一个浮窗。 2.跳转至Activity B，此时浮窗可以正常显示。 3.返回Activity A，调用FloatingX.control(FLOAT_TAG).hide()隐藏浮窗 4.再次跳转至Activity B，此时浮窗也是处于隐藏状态。 **5.然后在Activity B调用FloatingX.control(FLOAT_TAG).show()，这时浮窗无法正常显示，但是返回Activity A时，发现浮窗可以正常显示。**
> > 跟踪源代码发现，错误是发生在这一步： ![image](https://private-user-images.githubusercontent.com/11657383/323858334-7270215b-195e-4b56-8749-9ed2e2c50603.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MTQ3MDUsIm5iZiI6MTcxMzUxNDQwNSwicGF0aCI6Ii8xMTY1NzM4My8zMjM4NTgzMzQtNzI3MDIxNWItMTk1ZS00YjU2LTg3NDktOWVkMmUyYzUwNjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDA4MTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2ODg2NjA1NTQ3YmFjYTBmM2FlY2VlNTJhNjY3OWJjMTBhMTRkMWUyYzFkNzY5M2UxOTJhOGM0ZWFmYjdhYmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SKq0qzYuqIFZesimGP0B8jYLjqmLP5DDh2y9128F0G0) 在Activity B中的containerGroupView依旧是Activity A的DecorView，所以实际是添加在Activity A上显示，而B页面无法及时显示。
> 
> B Activity - show()展示时机是onResume之前吗，如果是的话那不行，目前浮窗的插入时机监控是在onResume里做的

是在OnResume中做的
![image](https://github.com/Petterpx/FloatingX/assets/11657383/af741f8a-561b-4518-9f29-f45f5904f6c6)

**Comment by gumaola** [comment]
在测试工程Sample app中也可以复现此问题：
1.针对浮窗1，不给予权限，降级为app层级浮窗。
2.首页点击“隐藏全局悬浮窗”，此时浮窗1被隐藏
3.首页点击“进入测试页面”->点击“进入多浮窗页面”->点击“显示全局悬浮窗（tag1）”，此时浮窗1依旧无法显示，仅当返回上一页后才会显示浮窗1

**Comment by gumaola** [comment]
> > 在测试工程Sample app中也可以复现此问题： 1.针对浮窗1，不给予权限，降级为app层级浮窗。 2.首页点击“隐藏全局悬浮窗”，此时浮窗1被隐藏 3.首页点击“进入测试页面”->点击“进入多浮窗页面”->点击“显示全局悬浮窗（tag1）”，此时浮窗1依旧无法显示，仅当返回上一页后才会显示浮窗1
> 
> 感谢反馈，已修复，请更新到2.0.7即可

感谢您的修正，从我的设备上看，上述不显示的问题已经得到修正。不过我又发现一个新的问题（版本2.0.7）。

同样可以在Sample上重现：
1.针对浮窗1，不给予权限，降级为app层级浮窗。
2.首页点击“隐藏全局悬浮窗”，此时浮窗1被隐藏
3.首页点击“进入测试页面”->点击“进入黑名单页面”->点击“显示全局悬浮窗”。此时悬浮窗不会被显示，没有问题。
4.**点击返回键，返回首页。点击“显示全局悬浮窗”，此时悬浮窗无法显示**。

根据代码，发现错误原因是在：
![image](https://github.com/Petterpx/FloatingX/assets/11657383/b0f7cf2a-c3ac-4950-af74-b9977ec89013)

此时fxView不知道何时已经呗attach到MainActivity的DecorView中了，所以走不到下一步。

**Comment by Petterpx** [comment]
> > > 在测试工程Sample app中也可以复现此问题： 1.针对浮窗1，不给予权限，降级为app层级浮窗。 2.首页点击“隐藏全局悬浮窗”，此时浮窗1被隐藏 3.首页点击“进入测试页面”->点击“进入多浮窗页面”->点击“显示全局悬浮窗（tag1）”，此时浮窗1依旧无法显示，仅当返回上一页后才会显示浮窗1
> > 
> > 
> > 感谢反馈，已修复，请更新到2.0.7即可
> 
> 感谢您的修正，从我的设备上看，上述不显示的问题已经得到修正。不过我又发现一个新的问题（版本2.0.7）。
> 
> 同样可以在Sample上重现： 1.针对浮窗1，不给予权限，降级为app层级浮窗。 2.首页点击“隐藏全局悬浮窗”，此时浮窗1被隐藏 3.首页点击“进入测试页面”->点击“进入黑名单页面”->点击“显示全局悬浮窗”。此时悬浮窗不会被显示，没有问题。 4.**点击返回键，返回首页。点击“显示全局悬浮窗”，此时悬浮窗无法显示**。
> 
> 根据代码，发现错误原因是在： ![image](https://private-user-images.githubusercontent.com/11657383/324703186-b0f7cf2a-c3ac-4950-af74-b9977ec89013.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzEwNjAsIm5iZiI6MTcxMzg3MDc2MCwicGF0aCI6Ii8xMTY1NzM4My8zMjQ3MDMxODYtYjBmN2NmMmEtYzNhYy00OTUwLWFmNzQtYjk5NzdlYzg5MDEzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDExMTI0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMGFkZjA4ODdjMjZkNTQyZDBkNWU0YzRjZmFhNTE5N2MxYzhhNTUyYmNhYTJiM2NmYmJmNzdhNWRiMGIzY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LgwPtDbM5Eetv84xlIyuvKihoVG2LbxWXZVPW4j66nE)
> 
> 此时fxView不知道何时已经呗attach到MainActivity的DecorView中了，所以走不到下一步。

这是一个比较复杂的流程问题，得debug一会，大概知道原因是因为fx的状态监测异常导致

**Comment by gumaola** [comment]
感谢，我个人暂时的解决办法就是修改了show()函数逻辑
![image](https://github.com/Petterpx/FloatingX/assets/11657383/596fdf10-0adf-4338-8354-72882565401d)

**Comment by Petterpx** [comment]
> 感谢，我个人暂时的解决办法就是修改了show()函数逻辑 ![image](https://private-user-images.githubusercontent.com/11657383/325089204-596fdf10-0adf-4338-8354-72882565401d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzkzOTgsIm5iZiI6MTcxMzkzOTA5OCwicGF0aCI6Ii8xMTY1NzM4My8zMjUwODkyMDQtNTk2ZmRmMTAtMGFkZi00MzM4LTgzNTQtNzI4ODI1NjU0MDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA2MTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyN2U3MTMxNWE3YmQxMGY3NzQ1NjYxOWMxYTg4MjQ1NjVhYzVhNzU2ZDdkMTVhZDI2YzVkNDkyNzYwOTE1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y0soGnGMHeb60oPu5KM6676wAyr8IHOEwNwDg9dShCA)

是的，这里可以兜底，但主要问题原因不是在show()方法,可以先这样处理

**Comment by Petterpx** [comment]
> > 感谢，我个人暂时的解决办法就是修改了show()函数逻辑 ![image](https://private-user-images.githubusercontent.com/11657383/325089204-596fdf10-0adf-4338-8354-72882565401d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5MzkzOTgsIm5iZiI6MTcxMzkzOTA5OCwicGF0aCI6Ii8xMTY1NzM4My8zMjUwODkyMDQtNTk2ZmRmMTAtMGFkZi00MzM4LTgzNTQtNzI4ODI1NjU0MDFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDA2MTEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyN2U3MTMxNWE3YmQxMGY3NzQ1NjYxOWMxYTg4MjQ1NjVhYzVhNzU2ZDdkMTVhZDI2YzVkNDkyNzYwOTE1MzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y0soGnGMHeb60oPu5KM6676wAyr8IHOEwNwDg9dShCA)
> 
> 是的，这里可以兜底，但主要问题原因不是在show()方法,可以先这样处理

抱歉久等了，更新到2.0.9即可修复此问题
