### ISSUE TITLE
有没有点击悬浮窗外部消失的方法

### ISSUE THREAD

**Issue by Jasperben** [Petterpx/FloatingX#151]
有没有点击悬浮窗外部消失的方法
类似dialog的setCanceledOnTouchOutside方法

**Comment by Petterpx** [comment]
> 有没有点击悬浮窗外部消失的方法 类似dialog的setCanceledOnTouchOutside方法

没有啊好兄弟，原理也很简单，dialog点击外部能取消的原因是，dialog外部阴影也属于dialog一部分啊，而浮窗没法做这种事，或者说，如果这样做，就要实现事件透传，以及浮窗层级问题。
