### ISSUE TITLE
show()方法没调用的时候，updateViewContent没有效果

### ISSUE THREAD

**Issue by Xing94** [Petterpx/FloatingX#152]
**你的Fx版本是多少**
最新版本

**遇到了什么问题**
使用updateViewContent修改控件的属性失效

**可复现的示例代码 或者 复现步骤**
updateViewContent方法调用在show方法之前，当show方法没有没调用，先使用updateViewContent方法的时候，updateViewContent的内容会失效，因为getViewHolder得到的viewHolder是null，可以在 provider.apply(getViewHolder() ?: return)之前调用一下updateEnableStatusAndCheckCanShow()得到正确的viewholder

**Comment by Petterpx** [comment]
> updateEnableStatusAndCheckCanShow

因为fx显示浮窗是懒加载的处理，在show之前，浮窗并不会初始化，故updateViewContent不会生效。
