### ISSUE TITLE
小米手机第一次弹悬浮窗切换页面悬浮窗自动消失了

### ISSUE THREAD

**Issue by JustinXiang** [Petterpx/FloatingX#153]
**你的Fx版本是多少**
2.1.0
**遇到了什么问题**
小米手机第一次弹悬浮窗切换页面悬浮窗自动消失了，第二次弹悬浮窗才能一直在
**可复现的示例代码 或者 复现步骤**

**Comment by Petterpx** [comment]
> **你的Fx版本是多少** 2.1.0 **遇到了什么问题** 小米手机第一次弹悬浮窗切换页面悬浮窗自动消失了，第二次弹悬浮窗才能一直在 **可复现的示例代码或者复现步骤**

有具体的示例代码吗，你弹悬浮窗的逻辑在哪里写着，是否可以在simple复现？

**Comment by JustinXiang** [comment]
private fun initFloat(){
FxAppHelper.builder().apply {
                setContext(this)
                setLayout(R.layout.dialog_message)
                setEnableEdgeAdsorption(false)
                setDisplayMode(FxDisplayMode.ClickOnly)
                setGravity(FxGravity.TOP_OR_CENTER)
                setScopeType(FxScopeType.APP)
            }
        messageFloatX = FloatingX.install(builder.build())
}
fun showFloat(){
        messageFloatX?.show()
    }
逻辑写在baseActivity中。每次都会出现这种情况

**Comment by JustinXiang** [comment]
> > **你的Fx版本是多少** 2.1.0 **遇到了什么问题** 小米手机第一次弹悬浮窗切换页面悬浮窗自动消失了，第二次弹悬浮窗才能一直在 **可复现的示例代码或者复现步骤**
> 
> 有具体的示例代码吗，你弹悬浮窗的逻辑在哪里写着，是否可以在simple复现？

private fun initFloat(){
FxAppHelper.builder().apply {
setContext(this)
setLayout(R.layout.dialog_message)
setEnableEdgeAdsorption(false)
setDisplayMode(FxDisplayMode.ClickOnly)
setGravity(FxGravity.TOP_OR_CENTER)
setScopeType(FxScopeType.APP)
}
messageFloatX = FloatingX.install(builder.build())
}
fun showFloat(){
messageFloatX?.show()
}
逻辑写在baseActivity中。每次都会出现这种情况

**Comment by Petterpx** [comment]
> install

1. 检查你的initFloat() 时机，不要放到base里频繁 init。
2. 每次调用 Floatingx.install() 内部都会取消之前的浮窗(根据tag而定)，重新安装新的，故会出现切换页面后需要重复show()。
3. fx支持多浮窗，具体根据tag而定，在你的代码里，FxAppHelper.builder() 里并没有设置 setTag(xx)，故tag为默认值，所以每次操作的都为默认浮窗；
4. 根据你的业务场景，如果你需要多页面使用浮窗，建议将上述配置添加到Application中调用，或者单独增加相应的静态浮窗管理类。如何判断浮窗是否已经存在，可以调用 Floatingx.isInstalled(tag) 进行判断，从而更合理的进行调度。
5. 如果你的业务场景并不需要全局浮窗，那么建议使用局部浮窗或者增加浮窗 黑名单 配置。

总之，建议多看文档，多看源码。这种过于基础操作的问题 并不值得仓库维护者来解答。

**Comment by Petterpx** [comment]
> > install
> 
> 1. 检查你的initFloat() 时机，不要放到base里频繁 init。
> 2. 每次调用 Floatingx.install() 内部都会取消之前的浮窗(根据tag而定)，重新安装新的，故会出现切换页面后需要重复show()。
> 3. fx支持多浮窗，具体根据tag而定，在你的代码里，FxAppHelper.builder() 里并没有设置 setTag(xx)，故tag为默认值，所以每次操作的都为默认浮窗；
> 4. 根据你的业务场景，如果你需要多页面使用浮窗，建议将上述配置添加到Application中调用，或者单独增加相应的静态浮窗管理类。如何判断浮窗是否已经存在，可以调用 Floatingx.isInstalled(tag) 进行判断，从而更合理的进行调度。
> 5. 如果你的业务场景并不需要全局浮窗，那么建议使用局部浮窗或者增加浮窗 黑名单 配置。
> 
> 总之，建议多看文档，多看源码。这种过于基础操作的问题   并不值得仓库维护者来解答。
@JustinXiang
