### ISSUE TITLE
锁屏然后亮屏 然后dialog里面显示floating，创建在了dialog下面

### ISSUE THREAD

**Issue by Jasperben** [Petterpx/FloatingX#154]
![image](https://github.com/Petterpx/FloatingX/assets/15630036/ac89792f-5265-4d51-892d-617d6257d234)

**Comment by Petterpx** [comment]
> ![image](https://private-user-images.githubusercontent.com/15630036/336368474-ac89792f-5265-4d51-892d-617d6257d234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTAwNjYsIm5iZiI6MTcxNzQ4OTc2NiwicGF0aCI6Ii8xNTYzMDAzNi8zMzYzNjg0NzQtYWM4OTc5MmYtNTI2NS00ZDUxLTg5MmQtNjE3ZDYyNTdkMjM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4MjkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZmI1OWZmNTUyZDdmMzA0MjMxMDA1ZDFhMjhjZWJhN2UyYjZjMDM4NzRiMTIzNzEyZjdjMjljNThkZmRmMDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a2GCUpJ0I6zAQf1AE8mJeMYr6rckkhChuGziWOvhgFw)

Fx的浮窗，对于Activity、Fragment是展示在 decorView上，故肯定是在你dialog之下，你的场景，你可以看看局部浮窗，或者将scopeType改为System

**Comment by Jasperben** [comment]
![image](https://github.com/Petterpx/FloatingX/assets/15630036/47e3cc00-f990-42ec-8b68-720e04f8aad7)

快速点击执行下面代码，前几次还能正常创建  但是后面就显示不出来

**Comment by Petterpx** [comment]
> ![image](https://private-user-images.githubusercontent.com/15630036/336374262-47e3cc00-f990-42ec-8b68-720e04f8aad7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTEzMTAsIm5iZiI6MTcxNzQ5MTAxMCwicGF0aCI6Ii8xNTYzMDAzNi8zMzYzNzQyNjItNDdlM2NjMDAtZjk5MC00MmVjLThiNjgtNzIwZTA0ZjhhYWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4NTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NTBiNTNlNDQ2ZGZhNmM5ZDY1NDc2MWJkZWFmY2ZiMmQ5MDUyMzU4NjhhMmI2MzlmYTczYjY3YjU0NjU5MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1UHCSINURpjICiger4fcrUg193QPvkcsT7Nm62aRV5k) ![image](https://private-user-images.githubusercontent.com/15630036/336376179-36ef29fd-4b10-4042-a396-cedab516a635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0OTEzMTAsIm5iZiI6MTcxNzQ5MTAxMCwicGF0aCI6Ii8xNTYzMDAzNi8zMzYzNzYxNzktMzZlZjI5ZmQtNGIxMC00MDQyLWEzOTYtY2VkYWI1MTZhNjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA4NTAxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNDcyMGY0NDZjNzFlODZiYzVlMzdmMWZlNDMwMmVhYzY3YmY4NGFmOWNiZjBjODI1ZTBjMDVlODNiMmU2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3EJ5gpskawgvSVZ9x4GZOthgt3g81qZ_XcjZXJal8os)
> 
> 快速点击执行下面代码，前几次还能正常创建 但是后面就显示不出来 log只执行了update enableFx: [true] 后面没执行

晚点我试试，还有并不需要每次都初始化helper进行show,建议判断是否存在浮窗后再进行初始化或者其他操作。这里涉及到权限申请、动画等流程，猜测某段逻辑应该卡住了。

**Comment by Petterpx** [comment]
> ![image](https://private-user-images.githubusercontent.com/15630036/336374262-47e3cc00-f990-42ec-8b68-720e04f8aad7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5ODgwOTYsIm5iZiI6MTcxNzk4Nzc5NiwicGF0aCI6Ii8xNTYzMDAzNi8zMzYzNzQyNjItNDdlM2NjMDAtZjk5MC00MmVjLThiNjgtNzIwZTA0ZjhhYWQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDAyNDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYTUwOTI1NDMyYjMyM2Y4NWU5NWFjMzg5NDk4ZDBkY2Y0ZDI1ZmZjNWUyZDk2YTM0MDc5MWVlNWY4Nzc1NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1kBSYpjKf4Be2IgqH5nw86SA5Hh3rlOQnFyCXShAl8g) ![image](https://private-user-images.githubusercontent.com/15630036/336376179-36ef29fd-4b10-4042-a396-cedab516a635.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5ODgwOTYsIm5iZiI6MTcxNzk4Nzc5NiwicGF0aCI6Ii8xNTYzMDAzNi8zMzYzNzYxNzktMzZlZjI5ZmQtNGIxMC00MDQyLWEzOTYtY2VkYWI1MTZhNjM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDAyNDk1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2YjJjMWQ2MGViODY5ODNkNTg0NjJjNmU2NmIxOTA1ODI1YzBhZjg5NjUzZTdlYjU0YmE4YjgzNWRhZmY5ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jQKcBwe0Uc_kE1gJt_aGZGF9u5FN3-q5BCyLFxjBQ9g)
> 
> 快速点击执行下面代码，前几次还能正常创建 但是后面就显示不出来 log只执行了update enableFx: [true] 后面没执行

<img width="1355" alt="image" src="https://github.com/Petterpx/FloatingX/assets/41142188/232ad8c3-2817-4240-b172-0f6f8bf0110b">
这边没有复现，你可以试试simple中是否可以复现，如果可以，开新的分支后，我这边再进行下一步排查
