### ISSUE TITLE
全屏的时候为啥 状态栏不会被覆盖

### ISSUE THREAD

**Issue by wlwanglun** [Petterpx/FloatingX#155]
我把FxSystemContainerView 默认改成MATCH_PARENT
 wl = WindowManager.LayoutParams().apply {
            width = helper.layoutParams?.width ?: WindowManager.LayoutParams.MATCH_PARENT
            height = helper.layoutParams?.height ?: (WindowManager.LayoutParams.MATCH_PARENT + 5000)
            format = PixelFormat.RGBA_8888
            gravity = Gravity.TOP or Gravity.START
            // 设置需要覆盖的系统窗口
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                layoutInDisplayCutoutMode =
                    WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES
            }
            // 如果是Android 11及以上，需要额外设置
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                layoutInDisplayCutoutMode =
                    WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS
            }
            flags =
                WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL or WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or WindowManager.LayoutParams.FLAG_FULLSCREEN
            type =
                WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
        }

**Comment by Petterpx** [comment]
> 我把FxSystemContainerView 默认改成MATCH_PARENT wl = WindowManager.LayoutParams().apply { width = helper.layoutParams?.width ?: WindowManager.LayoutParams.MATCH_PARENT height = helper.layoutParams?.height ?: (WindowManager.LayoutParams.MATCH_PARENT + 5000) format = PixelFormat.RGBA_8888 gravity = Gravity.TOP or Gravity.START // 设置需要覆盖的系统窗口 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) { layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES } // 如果是Android 11及以上，需要额外设置 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) { layoutInDisplayCutoutMode = WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS } flags = WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL or WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or WindowManager.LayoutParams.FLAG_FULLSCREEN type = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY }

试试这样呢 
```kotlin
wl = WindowManager.LayoutParams().apply {
            width = helper.layoutParams?.width ?: WindowManager.LayoutParams.WRAP_CONTENT
            height = helper.layoutParams?.height ?: WindowManager.LayoutParams.WRAP_CONTENT
            format = PixelFormat.RGBA_8888
            gravity = Gravity.TOP or Gravity.START
            flags =
                WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL or
                        WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE or
                        WindowManager.LayoutParams.FLAG_TRANSLUCENT_STATUS or
                        WindowManager.LayoutParams.FLAG_FULLSCREEN or
                        WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN or
                        WindowManager.LayoutParams.FLAG_LAYOUT_NO_LIMITS

            type = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY
            } else {
                WindowManager.LayoutParams.TYPE_SYSTEM_ALERT
            }
        }
```

**Comment by wlwanglun** [comment]
wl = WindowManager.LayoutParams().apply {
            width = helper.layoutParams?.width ?: WindowManager.LayoutParams.MATCH_PARENT
            height = helper.layoutParams?.height ?: WindowManager.LayoutParams.MATCH_PARENT
            format = PixelFormat.TRANSLUCENT
            gravity = (Gravity.TOP or Gravity.START)
            // 设置需要覆盖的系统窗口
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                layoutInDisplayCutoutMode =
                    WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES
            }
            // 如果是Android 11及以上，需要额外设置
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R) {
                layoutInDisplayCutoutMode =
                    WindowManager.LayoutParams.LAYOUT_IN_DISPLAY_CUTOUT_MODE_ALWAYS
            }
            flags = (WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED
                    or WindowManager.LayoutParams.FLAG_DISMISS_KEYGUARD
                    or WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON
                    or WindowManager.LayoutParams.FLAG_FULLSCREEN
                    or WindowManager.LayoutParams.FLAG_LAYOUT_IN_SCREEN
                    or WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS
                    )
            type =
                WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY

        }
可以了
