### ISSUE TITLE
setEnableAllBlackClass 没有这个方法啊

### ISSUE THREAD

**Issue by DalesDawson** [Petterpx/FloatingX#156]
setEnableAllBlackClass 没有这个方法啊，设置了黑名单貌似没生效

**Comment by DalesDawson** [comment]
而且加了addInstallBlackClass之后所有界面都没有悬浮窗了， setEnableAllInstall(true)

**Comment by Petterpx** [comment]
> 而且加了addInstallBlackClass之后所有界面都没有悬浮窗了， setEnableAllInstall(true)

1. 文档问题，忘记了更新，请调用setEnableAllInstall() 即可控制是否运行全部展示。
2. addInstallBlackClass之后没有悬浮窗，先尝试一下simple是否可复现

**Comment by DalesDawson** [comment]
刚刚也加你wx了，其实我有个需求是这样，我有个activity为了保活，我缩小了界面，然后上一个页面就没有悬浮窗了

**Comment by DalesDawson** [comment]
我发现悬浮窗一直在我缩小的那个activity里面，怎么使其他页面也能展示悬浮窗呢
