### ISSUE TITLE
如何动态更新 运行时配置（链接如下）

### ISSUE THREAD

**Issue by jeromekai** [Petterpx/FloatingX#159]
https://cskf7l0wab.feishu.cn/wiki/wikcn5aOV8YqPy29J3Q4k4uGGFd
` 
this.iFxScopeControl = FxScopeHelper.builder().setLayout(R.layout.view_float_action).setEnableLog(true, TAG)
                .setTopBorderMargin(ScreenUtil.dp2px(80f)).setGravity(FxGravity.RIGHT_OR_TOP).setOffsetXY(0, 100)
                .setTouchListener(fxFloatTouchListener).setOnClickListener(fxFloatClickListener).build().toControl(this);
        this.iFxScopeControl.show();
`

  iFxScopeControl.getConfigControl().setBorderMargin(ScreenUtil.dp2px(80f), 0, inputView.getTop(), 0); 
  如果是这样更新貌似没效果

**Comment by Petterpx** [comment]
> setBorderMargin

试试 simple 是否可以复现，目前没发现有问题。
