### ISSUE TITLE
浮窗比较大的时候，靠边吸附有问题，会一直靠左边吸附

### ISSUE THREAD

**Issue by littlezan** [Petterpx/FloatingX#160]
**你的Fx版本是多少**
最新版本

**遇到了什么问题**
浮窗比较大的时候，靠边吸附有问题，会一直靠左边吸附
<img width="451" alt="image" src="https://github.com/Petterpx/FloatingX/assets/5358278/1d90fec2-97e5-4f73-9873-c628ca4fd029">

**可复现的示例代码 或者 复现步骤**
修改一下布局文件的大小即可复现
<img width="1102" alt="image" src="https://github.com/Petterpx/FloatingX/assets/5358278/7efddd4a-2876-47c3-ac7e-04e278fe4caf">

**Comment by littlezan** [comment]
我这样改，问题解决了：
<img width="1092" alt="image" src="https://github.com/Petterpx/FloatingX/assets/5358278/5c2866a0-da3e-4d89-8a42-5affc3ddcb98">

**Comment by Petterpx** [comment]
> 我这样改，问题解决了： <img alt="image" width="1092" src="https://private-user-images.githubusercontent.com/5358278/341420915-5c2866a0-da3e-4d89-8a42-5affc3ddcb98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMjMwNTQsIm5iZiI6MTcxOTAyMjc1NCwicGF0aCI6Ii81MzU4Mjc4LzM0MTQyMDkxNS01YzI4NjZhMC1kYTNlLTRkODktOGE0Mi01YWZmYzNkZGNiOTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjJUMDIxOTE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjU4YmE5YWIwMWYzMGI4ZTIwZmFjNWNiNGM4YjkzNmY3ODg2M2YxNDg1MTVjMTllNjJlYTVkZTIxM2MzYWI3ZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AJPTOfHq62dTQvhmezNQ0AcjLCtF5As1Ss90HvYphmY">

其实就是中心点的问题，之前是按照view左上角为坐标系，从而导致异常

**Comment by Petterpx** [comment]
已修复，更新到2.1.1即可 ：）
