### ISSUE TITLE
支持ComposeView

### ISSUE THREAD

**Issue by MingYubmy** [Petterpx/FloatingX#162]
**在尝试使用ComposeView时会发生报错**
_java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from com.petterp.floatingx.view.FxSystemContainerView{6385a0d V.E...... ......I. 0,0-0,0}_

**希望可以尝试支持一下Compose，感谢！**

**Comment by Petterpx** [comment]
> **在尝试使用ComposeView时会发生报错** _java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from com.petterp.floatingx.view.FxSystemContainerView{6385a0d V.E...... ......I. 0,0-0,0}_
> 
> **希望可以尝试支持一下Compose，感谢！**

好的，这周处理

**Comment by Petterpx** [comment]
> **在尝试使用ComposeView时会发生报错** _java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from com.petterp.floatingx.view.FxSystemContainerView{6385a0d V.E...... ......I. 0,0-0,0}_
> 
> **希望可以尝试支持一下Compose，感谢！**

你可以先使用App浮窗，并更新自己的appcompat库到1.3.0及以上即可。系统浮窗晚些时候支持

**Comment by MingYubmy** [comment]
> > **在尝试使用ComposeView时会发生报错** _java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from com.petterp.floatingx.view.FxSystemContainerView{6385a0d V.E...... ......I. 0,0-0,0}_
> > **希望可以尝试支持一下Compose，感谢！**
> 
> 你可以先使用App浮窗，并更新自己的appcompat库到1.3.0及以上即可。系统浮窗晚些时候支持

好的，感谢

**Comment by Petterpx** [comment]
> **在尝试使用ComposeView时会发生报错** _java.lang.IllegalStateException: ViewTreeLifecycleOwner not found from com.petterp.floatingx.view.FxSystemContainerView{6385a0d V.E...... ......I. 0,0-0,0}_
> 
> **希望可以尝试支持一下Compose，感谢！**

已支持，请更新到2.2.1即可，额外引入下面的Module，并在你的AppHelper构造时调用     enableComposeSupport() 即可。
```kotlin
  FloatingX.install {
            // see this
            enableComposeSupport()
}.show()
```
```groovy
 implementation "io.github.petterpx:floatingx-compose:2.2.1"
```
