### ISSUE TITLE
想问一下如果我的浮窗内有2部分view，希望触摸上半部分的时候view能拖动浮窗位置，下半部分只响应内部事件，如何处理比较好

### ISSUE THREAD

**Issue by WayneLyn** [Petterpx/FloatingX#165]
例如layout是个linenarlayout，包含一个header，下面是一个recyclerview，我希望header可以拖动浮窗，recyclerview则响应滚动，怎么处理呀？可以提供下demo吗

**Comment by Petterpx** [comment]
> 例如layout是个linenarlayout，包含一个header，下面是一个recyclerview，我希望header可以拖动浮窗，recyclerview则响应滚动，怎么处理呀？可以提供下demo吗

晚点更新一下库就可以了，功能已支持，不过有点小bug。大致这么写到时候就行：
<img width="764" alt="image" src="https://github.com/user-attachments/assets/16ef230b-ef4e-4148-8cda-c1f9e31efb67">

**Comment by WayneLyn** [comment]
感谢回复。我这边是通过DisplayMode来设置，在down的时候检测区域设置对应的displayMode。也有点bug。当要拖动的时候，得点击一下头部区域，下次再拖动才行。
<img width="838" alt="image" src="https://github.com/user-attachments/assets/cb75165d-ac44-4e99-9adc-894e141a32b2">

**Comment by Petterpx** [comment]
> 感谢回复。我这边是通过DisplayMode来设置，在down的时候检测区域设置对应的displayMode。也有点bug。当要拖动的时候，得点击一下头部区域，下次再拖动才行。 <img alt="image" width="838" src="https://private-user-images.githubusercontent.com/6802577/350657030-cb75165d-ac44-4e99-9adc-894e141a32b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NTk4ODgsIm5iZiI6MTcyMTQ1OTU4OCwicGF0aCI6Ii82ODAyNTc3LzM1MDY1NzAzMC1jYjc1MTY1ZC1hYzQ0LTRlOTktOWFkYy04OTRlMTQxYTMyYjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjBUMDcxMzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGVkNzBjMDMzNzRjM2JhM2FhNzkyY2Q3MWQ0NzQwYmU0YjAyMDg1MzY5NTYzODkzMTkxYmE4ZTIyNTQ2MzQzZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ki3GWXBcVyveX3yEsW7vl485C5z05XbNmEs7oVwQIo0">

主要原因是因为转发时机的问题，Fx onInterceptTouchEvent监听的回调实际上是在拦截方法最后调用，故导致了这个尴尬问题。

**Comment by Petterpx** [comment]
更新到2.2.1即可解决该问题，示例参照：
<img width="885" alt="image" src="https://github.com/user-attachments/assets/a4bb7e51-3761-4f79-8690-dd1a47af535e">
通过 control.checkPointerDownTouch(view or idRes) 你可以判断出当前手指点击位置是否处于你的view所在位置，从而轻松实现事件拦截。
