### ISSUE TITLE
依赖失败

### ISSUE THREAD

**Issue by JamesGZM** [Petterpx/FloatingX#167]
**你的Fx版本是多少**

2.2.1
**遇到了什么问题**
导入失败

**可复现的示例代码 或者 复现步骤**

2.1.1 导入正常 从 2.2.0 开始导入失败

日志

`Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform material3-1.1.1.aar (androidx.compose.material3:material3:1.1.1) to match attributes {artifactType=android-manifest, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.`

排查是导入了compose的问题

**Comment by JamesGZM** [comment]
还有个问题是 kotlin 版本太高

**Comment by JamesGZM** [comment]
添加排除 
` exclude group: 'androidx.compose.ui'`

` exclude group: 'androidx.compose.material3'`

成功依赖

**Comment by JamesGZM** [comment]
> 还有个问题是 kotlin 版本太高

版本破坏性太大 我回退到了 2.1.0

**Comment by JamesGZM** [comment]
> 添加排除 ` exclude group: 'androidx.compose.ui'`
> 
> ` exclude group: 'androidx.compose.material3'`
> 
> 成功依赖

kotlin 版本太高  回退到 2.1.0 了

**Comment by Petterpx** [comment]
尴尬了，在测试compose兼容结束后，忘了移除compose依赖，你更新到2.2.2即可

**Comment by Petterpx** [comment]
正在构建中，大概30分钟后即可依赖

**Comment by JamesGZM** [comment]
还存在 kotlin 版本太高问题 会构建不了 我的 kotlin 版本为1.5.21

**Comment by JamesGZM** [comment]
我在尝试升级 但是升级改动太大；gradle 插件版本 包括一些依赖版本全都要改

**Comment by Petterpx** [comment]
> 我在尝试升级 但是升级改动太大；gradle 插件版本 包括一些依赖版本全都要改

使用kotlin1.6.x 版本吧，因为appcompat升级到了1.3.0，但正常来说不至于有影响，如果你没有依赖fx-compose的话

**Comment by JamesGZM** [comment]
我试试 主要是项目里面用了 room 版本比较老

**Comment by JamesGZM** [comment]
替换为 kotlin 版本为 1.6.10之后 还是会
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.

**Comment by Petterpx** [comment]
appcompat1.3实际上是21年的版本了，严格来说正常的项目中版本都会比它高，至于kotlin版本，1.5.31是很老的版本，正常的项目目前也处于1.8.x+ 😂，

**Comment by JamesGZM** [comment]
没办法 好几年的老项目了。

**Comment by Petterpx** [comment]
> 替换为 kotlin 版本为 1.6.10之后 还是会 Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.

不科学，要不尝试 清下缓存，appcompat1.3不会影响kt版本

**Comment by Petterpx** [comment]
> > 替换为 kotlin 版本为 1.6.10之后 还是会 Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
> 
> 不科学，要不尝试 清下缓存，appcompat1.3不会影响kt版本

Invalidate Caches

**Comment by JamesGZM** [comment]
升级到1.7.1的 kotlin 版本也不行
确实不科学

**Comment by JamesGZM** [comment]
> > > 替换为 kotlin 版本为 1.6.10之后 还是会 Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.6.0.
> > 
> > 
> > 不科学，要不尝试 清下缓存，appcompat1.3不会影响kt版本
> 
> Invalidate Caches

我试试

**Comment by JamesGZM** [comment]
Invalidate Caches 无效
尝试升级了 gradle 插件版本 升级到 7.2.2了 
升级到1.7.1的 kotlin 版本

Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0,

还是一样的错误

**Comment by JamesGZM** [comment]
我回退到2.1.0版本了

**Comment by Petterpx** [comment]
> 我回退到2.1.0版本了

找到原因了，新增了fx-compose module之后，原以为不同的module是隔离的，结果依赖了floatingx之后，会默认把floatingx-compose也引入，从而导致了这个问题。

**Comment by Petterpx** [comment]
> > 我回退到2.1.0版本了
> 
> 找到原因了，新增了fx-compose module之后，原以为不同的module是隔离的，结果依赖了floatingx之后，会默认把floatingx-compose也引入，从而导致了这个问题。

不过很奇怪，有其他同学并没有问题。
![Uploading image.png…]()

**Comment by JamesGZM** [comment]
😖 那就神奇了 可能是老项目的问题 项目太老了

**Comment by Petterpx** [comment]
> 😖 那就神奇了 可能是老项目的问题 项目太老了

你是新依赖的，还是升级2.2.x后发现不行了

**Comment by JamesGZM** [comment]
以前版本比较老 还是 com.github.Petterpx:FloatingX:1.0-rc13的版本
当时直接升级到了 2.2.1 发现不兼容 直接编译报错了 排除掉了 项目中的 compose 依赖之后 就出现了这个问题

**Comment by JamesGZM** [comment]
我尝试回退版本 一直退到2.1.1 2.1.0是没有问题的

**Comment by Petterpx** [comment]
> Owner

和这个没关系，刚试了几个新项目，不会出现这种问题。

**Comment by JamesGZM** [comment]
> 以前版本比较老 还是 com.github.Petterpx:FloatingX:1.0-rc13的版本 当时直接升级到了 2.2.1 发现不兼容 直接编译报错了 排除掉了 项目中的 compose 依赖之后 就出现了这个问题

然后你更新了2.2.2 我是直接依赖了 排除项没有加了 也是 kotlin 版本过高的问题

**Comment by Petterpx** [comment]
> 我尝试回退版本 一直退到2.1.1 2.1.0是没有问题的

soga，那你可以先用2.1.1，没有什么bug，少了一些新功能暂时

**Comment by JamesGZM** [comment]
项目还是老构架 gradle版本也比较老 我尝试升级 kotlin 版本最高到了1.7.10 gradle 插件版本到7.2.2 同时 clean Invalidate Caches 都试过 所以很神奇

**Comment by Petterpx** [comment]
<img width="768" alt="image" src="https://github.com/user-attachments/assets/87731df0-2d52-4635-895c-d93d051e587d">
依赖是没有问题的，目前来看就是你项目的原因了。试试在build.gradle里统一一下kt的版本呢
defaultConfig {
 configurations.all {
            resolutionStrategy {
                force "org.jetbrains.kotlin:kotlin-stdlib:1.5.21" || 1.6.xx
            }
        }
}

**Comment by JamesGZM** [comment]
> <img alt="image" width="768" src="https://private-user-images.githubusercontent.com/41142188/350891434-87731df0-2d52-4635-895c-d93d051e587d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2Mzc5NTUsIm5iZiI6MTcyMTYzNzY1NSwicGF0aCI6Ii80MTE0MjE4OC8zNTA4OTE0MzQtODc3MzFkZjAtMmQ1Mi00NjM1LTg5NWMtZDkzZDA1MWU1ODdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA4NDA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUyZGY3MGRlZTE1ZTRiMjI2NmQ4OWVhYTQyZWI3ZTk0MjlhOGIyZTliODBmYzQ3MmI5NzIxMTk0MTgwZWRlYTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SA7sM7irQSILrWv77ktIGi-LUaP3Bey2gb6Qwoeu9Wk">
> 依赖是没有问题的，目前来看就是你项目的原因了。试试在build.gradle里统一一下kt的版本呢
> 
> ```groovy
> defaultConfig {
>  configurations.all {
>             resolutionStrategy {
>                 force "org.jetbrains.kotlin:kotlin-stdlib:1.5.21" || 1.6.xx
>             }
>         }
> }
> ```

不行 我把gradle 缓存删了  包括 clean Invalidate Caches


```
Class 'com.petterp.floatingx.view.FxViewHolder' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.5.1.
The class is loaded from /Users/admin/.gradle/caches/transforms-2/files-2.1/fd5f84409639f6453a0d4ba1c130cedd/jetified-floatingx-2.2.2-api.jar!/com/petterp/floatingx/view/FxViewHolder.class
```

用的是 2.2.2

**Comment by JamesGZM** [comment]
<img width="725" alt="image" src="https://github.com/user-attachments/assets/c7e7699f-8f83-4512-a0f1-2ea38b3748e1">
确实比较奇怪 用命令看替换也是成功了的 就是还是一样报错

**Comment by Petterpx** [comment]
@JamesGZM 已修复，更新到2.2.3即可
