### ISSUE TITLE
根据网络图片来显示不同大小的飘窗

### ISSUE THREAD

**Issue by Neroliuxx** [Petterpx/FloatingX#171]
这边想尝试做根据网络图片来显示不同大小的飘窗 发现gravity在right的飘窗初始状态都会超出屏幕 拖动一下就会正常 这种情况是得有什么配置吗

**Comment by Petterpx** [comment]
> 这边想尝试做根据网络图片来显示不同大小的飘窗 发现gravity在right的飘窗初始状态都会超出屏幕 拖动一下就会正常 这种情况是得有什么配置吗

主要原因是因为 onSizeChanged() 触发时，浮窗没有同步边界，这边调整一下。

**Comment by Petterpx** [comment]
更新到2.2.4即可解决
