### ISSUE TITLE
悬浮窗会从上一个位置跳动到实际位置

### ISSUE THREAD

**Issue by qiang54huang20231012** [Petterpx/FloatingX#172]
**你的Fx版本是多少**
2.2.3
**遇到了什么问题**
需求是，显示一个悬浮窗，包含多个图标，显示n秒后，只保留一个图标，其他图标设为Gone，这样view的尺寸就发生了变化
问题是，在其他图标为Gone，view尺寸发生变化时，悬浮窗会从上一个位置跳动到实际位置，然后才显示只保留一个图标的悬浮窗

**可复现的示例代码 或者 复现步骤**

**Comment by Petterpx** [comment]
> **你的Fx版本是多少** 2.2.3 **遇到了什么问题** 需求是，显示一个悬浮窗，包含多个图标，显示n秒后，只保留一个图标，其他图标设为Gone，这样view的尺寸就发生了变化 问题是，在其他图标为Gone，view尺寸发生变化时，悬浮窗会从上一个位置跳动到实际位置，然后才显示只保留一个图标的悬浮窗
> 
> **可复现的示例代码 或者 复现步骤**

和 #171 一样，明天再来定位处理，今天改了其他问题，要去打游戏了。

**Comment by Petterpx** [comment]
更新到2.2.4即可解决。

**Comment by qiang54huang20231012** [comment]
Hi，更新到2.2.4问题仍然存在呢

**Comment by Petterpx** [comment]
> Hi，更新到2.2.4问题仍然存在呢

sync一下，然后录个视频呢？并附带你的可复现示例

**Comment by qiang54huang20231012** [comment]
```
private val mCheckRemoveTask = object : Runnable {
        override fun run() {
            val currentTime = System.currentTimeMillis()
            Log.d(TAG, "run: toolkit view shrink currentTime: " +
                    "$currentTime mLastOperateTime: $mLastOperateTime  interval: ${currentTime - mLastOperateTime}")
            if (currentTime - mLastOperateTime >= 5000) {
                // 5s未操作，缩小工具栏
                recorderToolView.switchViewType(RecorderToolView.TYPE_SMALL)
                viewType = RecorderToolView.TYPE_SMALL
                mHandler.removeCallbacks(this)
            } else {
                // 继续执行定时任务
                mHandler.postDelayed(this, checkInterval)
            }
        }
    }
```

**Comment by qiang54huang20231012** [comment]
在服务中设置定时任务
```
private val mCheckRemoveTask = object : Runnable {
        override fun run() {
            val currentTime = System.currentTimeMillis()
            if (currentTime - mLastOperateTime >= 5000) {
                // 5s未操作，缩小工具栏
                toolView.switchViewType(RecorderToolView.TYPE_SMALL)
                viewType = RecorderToolView.TYPE_SMALL
                mHandler.removeCallbacks(this)
            } else {
                // 继续执行定时任务
                mHandler.postDelayed(this, checkInterval)
            }
        }
    }
```
toolView.switchViewType(RecorderToolView.TYPE_SMALL) 如下：
```
fun switchViewType(type: Int) {
        when (type) {
            TYPE_SMALL -> {
                recordToolBinding.stopButton.visibility = View.GONE
                recordToolBinding.pauseButton.visibility = View.GONE
            }
            TYPE_ALL_CONTROLS -> {
                recordToolBinding.micButton.visibility = View.VISIBLE
                recordToolBinding.stopButton.visibility = View.VISIBLE
                recordToolBinding.pauseButton.visibility = View.VISIBLE
            }
        }
    }
```
下附视频

https://github.com/user-attachments/assets/47be0113-c641-4486-904c-8b0b3c99ffa8

**Comment by Petterpx** [comment]
> 在服务中设置定时任务
> 
> ```
> private val mCheckRemoveTask = object : Runnable {
>         override fun run() {
>             val currentTime = System.currentTimeMillis()
>             if (currentTime - mLastOperateTime >= 5000) {
>                 // 5s未操作，缩小工具栏
>                 toolView.switchViewType(ToolView.TYPE_SMALL)
>                 viewType = ToolView.TYPE_SMALL
>                 mHandler.removeCallbacks(this)
>             } else {
>                 // 继续执行定时任务
>                 mHandler.postDelayed(this, checkInterval)
>             }
>         }
>     }
> ```
> 
> toolView.switchViewType(ToolView.TYPE_SMALL) 如下：
> 
> ```
> fun switchViewType(type: Int) {
>         when (type) {
>             TYPE_SMALL -> {
>                 recordToolBinding.stopButton.visibility = View.GONE
>                 recordToolBinding.pauseButton.visibility = View.GONE
>             }
>             TYPE_ALL_CONTROLS -> {
>                 recordToolBinding.micButton.visibility = View.VISIBLE
>                 recordToolBinding.stopButton.visibility = View.VISIBLE
>                 recordToolBinding.pauseButton.visibility = View.VISIBLE
>             }
>         }
>     }
> ```
> 
> 下附视频
> 
>  Screen_recording_20240805_104353.mp4

本地试了一下，没有复现，你看看你的Fx配置呢？

**Comment by Petterpx** [comment]
暂时先关了。
