### ISSUE TITLE
希望黑名单可以使用类名来添加

### ISSUE THREAD

**Issue by android-1995** [Petterpx/FloatingX#173]
sdk使用的话，外部的class不能用MainActivity::class.java。希望能"com.petterp.floatingx.app.MainActivity"这样添加

**Comment by Petterpx** [comment]
👌

**Comment by Petterpx** [comment]
更新到2.2.5 即可。

**Comment by Petterpx** [comment]
> > 更新到2.2.5 即可。
> 
> 没看到相关提交？忘记提交了？

哈哈，这个commit漏了，功能的确支持了，但没push上去。中午再补上

**Comment by Petterpx** [comment]
更新到2.2.6即可 @android-1995
