### ISSUE TITLE
浮窗比较大，是否支持放大缩小的功能？

### ISSUE THREAD

**Issue by goodsfile** [Petterpx/FloatingX#176]

**Comment by goodsfile** [comment]
通过拖拽放大缩小，能放大全屏，能缩小到一定程度变成图标，这种能支持吗

**Comment by Petterpx** [comment]
> 通过拖拽放大缩小，能放大全屏，能缩小到一定程度变成图标，这种能支持吗

业务需求，自行实现，框架不负责此类逻辑。

**Comment by goodsfile** [comment]
缩小放大 这种也自己实现吗

**Comment by Petterpx** [comment]
> 缩小放大 这种也自己实现吗

是的，你可以自己自定义事件实现，fx暂时不处理这种功能。
