### ISSUE TITLE
改变弹框大小后调用move方法位置不正确

### ISSUE THREAD

**Issue by usernameSHQ** [Petterpx/FloatingX#177]
**你的Fx版本是多少**
2.2.6
**遇到了什么问题**
比实际填的位置高了好多
**可复现的示例代码 或者 复现步骤**
![306fc3be15f036ace1e54a1fc33ffa3](https://github.com/user-attachments/assets/27fffda5-787d-4f5f-a172-467fbb6ec755)
![b8ac214d554cf19cbc30ea917743da6](https://github.com/user-attachments/assets/c574338f-3ce6-42ac-9e82-92524756505a)
![f1a91b590a10b2640cb43a65dc903b6](https://github.com/user-attachments/assets/312b5367-e2d5-43ec-a340-5d1e93c3eb9d)

**Comment by Petterpx** [comment]
晚点排查一下
