### ISSUE TITLE
Compose浮窗改变尺寸会出现从上一个位置跳到当前位置

### ISSUE THREAD

**Issue by wao3** [Petterpx/FloatingX#178]
**你的Fx版本是多少**
2.2.6

**遇到了什么问题**
Compose浮窗改变尺寸会出现从上一个位置跳到当前位置

**可复现的示例代码 或者 复现步骤**
```kotlin
object FloatingCompose {
    fun install(context: MainActivity) {
        FloatingX.install {
            setContext(context)
            setTag("compose")
            enableComposeSupport()
            setScopeType(FxScopeType.SYSTEM)
            setLayoutView(
                ComposeView(context).apply {
                    setContent {
                        FloatingWindow()
                    }
                }
            )
            setEnableLog(true)
            setEdgeOffset(20f)
        }.show()
    }
}

@Composable
fun FloatingWindow() {
    var isOpen by remember { mutableStateOf(false) }
    val width by animateDpAsState(
        targetValue = if (isOpen) 400.dp else 40.dp,
        animationSpec = tween(durationMillis = 100, easing = FastOutSlowInEasing), label = ""
    )

    Box(
        modifier = Modifier
            .width(width)
            .height(40.dp)
            .clip(RoundedCornerShape(20.dp))
            .background(Color.LightGray)
    ) {
        Row(
            modifier = Modifier.fillMaxSize(),
            verticalAlignment = Alignment.CenterVertically
        ) {
            Box(
                modifier = Modifier
                    .size(40.dp)
                    .clip(CircleShape)
                    .background(Color.Blue)
                    .clickable {
                        isOpen = !isOpen
                    },
                contentAlignment = Alignment.Center
            ) {
                Text(
                    text = if (isOpen) "关" else "开",
                    color = Color.White,
                    fontSize = 20.sp,
                    fontWeight = FontWeight.Bold
                )
            }
        }
    }
}

```

[Screen_recording_20241004_180314.webm](https://github.com/user-attachments/assets/96324989-a6b3-428a-8efe-ace96337cd6e)

**Comment by Petterpx** [comment]
明天修复

**Comment by Petterpx** [comment]
> **你的Fx版本是多少** 2.2.6
> 
> **遇到了什么问题** Compose浮窗改变尺寸会出现从上一个位置跳到当前位置
> 
> **可复现的示例代码 或者 复现步骤**
> 
> ```kotlin
> object FloatingCompose {
>     fun install(context: MainActivity) {
>         FloatingX.install {
>             setContext(context)
>             setTag("compose")
>             enableComposeSupport()
>             setScopeType(FxScopeType.SYSTEM)
>             setLayoutView(
>                 ComposeView(context).apply {
>                     setContent {
>                         FloatingWindow()
>                     }
>                 }
>             )
>             setEnableLog(true)
>             setEdgeOffset(20f)
>         }.show()
>     }
> }
> 
> @Composable
> fun FloatingWindow() {
>     var isOpen by remember { mutableStateOf(false) }
>     val width by animateDpAsState(
>         targetValue = if (isOpen) 400.dp else 40.dp,
>         animationSpec = tween(durationMillis = 100, easing = FastOutSlowInEasing), label = ""
>     )
> 
>     Box(
>         modifier = Modifier
>             .width(width)
>             .height(40.dp)
>             .clip(RoundedCornerShape(20.dp))
>             .background(Color.LightGray)
>     ) {
>         Row(
>             modifier = Modifier.fillMaxSize(),
>             verticalAlignment = Alignment.CenterVertically
>         ) {
>             Box(
>                 modifier = Modifier
>                     .size(40.dp)
>                     .clip(CircleShape)
>                     .background(Color.Blue)
>                     .clickable {
>                         isOpen = !isOpen
>                     },
>                 contentAlignment = Alignment.Center
>             ) {
>                 Text(
>                     text = if (isOpen) "关" else "开",
>                     color = Color.White,
>                     fontSize = 20.sp,
>                     fontWeight = FontWeight.Bold
>                 )
>             }
>         }
>     }
> }
> ```
> 
>  Screen_recording_20241004_180314.webm

这个代码没有复现，你可以试试这个分支呢 https://github.com/Petterpx/FloatingX/tree/test/compose_move_rule

**Comment by Petterpx** [comment]
另外，请不要在全局浮窗中使用Activity作为context，避免内存泄漏
