### ISSUE TITLE
切换页面，floatingx闪烁

### ISSUE THREAD

**Issue by KaleidosChen** [Petterpx/FloatingX#179]
设置.setScopeType(FxScopeType.APP)后
切换页面的时候，悬浮框是在新页面中生成一个新的悬浮框，会产生消失-显示问题，而不是在原有位置上一直显示。
这个只能去修改scopeType为系统级，才能达到无缝显示悬浮框吗？

**Comment by Petterpx** [comment]
> 设置.setScopeType(FxScopeType.APP)后 切换页面的时候，悬浮框是在新页面中生成一个新的悬浮框，会产生消失-显示问题，而不是在原有位置上一直显示。 这个只能去修改scopeType为系统级，才能达到无缝显示悬浮框吗？

是的，FxScopeType.APP是应用内浮窗，原理是插入到Activity之上，所以会闪烁一下
