### ISSUE TITLE
旋转之后关闭当前页面,上一页面浮窗会没有

### ISSUE THREAD

**Issue by goodsfile** [Petterpx/FloatingX#180]
**你的Fx版本是多少**
2.2.6
**遇到了什么问题**
从A跳B,B旋转然后点击按钮关闭B,A的浮窗会没有
**可复现的示例代码 或者 复现步骤**
demo 可以复现

**Comment by Petterpx** [comment]
> **你的Fx版本是多少** 2.2.6 **遇到了什么问题** 从A跳B,B旋转然后点击按钮关闭B,A的浮窗会没有 **可复现的示例代码 或者 复现步骤** demo 可以复现

没有复现，附上视频呢

**Comment by goodsfile** [comment]
> > **你的Fx版本是多少** 2.2.6 **遇到了什么问题** 从A跳B,B旋转然后点击按钮关闭B,A的浮窗会没有 **可复现的示例代码 或者 复现步骤** demo 可以复现
> 
> 没有复现，附上视频呢

demo 又复现不了呢

**Comment by Petterpx** [comment]
> > > **你的Fx版本是多少** 2.2.6 **遇到了什么问题** 从A跳B,B旋转然后点击按钮关闭B,A的浮窗会没有 **可复现的示例代码 或者 复现步骤** demo 可以复现
> > 
> > 
> > 没有复现，附上视频呢
> 
> demo 又复现不了呢

这种就不确定了，理论上，这种问题存在的话，反馈的同学应该很多
