### ISSUE TITLE
降级为应用内浮窗

### ISSUE THREAD

**Issue by Vortex-hui** [Petterpx/FloatingX#183]
不同意权限，降级为应用内浮窗后，悬浮窗会与顶部有距离，系统悬浮窗则会到顶部，没有设置偏移量

**Comment by Vortex-hui** [comment]
顶部的距离应该是状态栏的高度，设置了全屏模式还是会有状态栏的高度

**Comment by Petterpx** [comment]
> 不同意权限，降级为应用内浮窗后，悬浮窗会与顶部有距离，系统悬浮窗则会到顶部，没有设置偏移量

OK，今天晚些时候修复

**Comment by Petterpx** [comment]
> 不同意权限，降级为应用内浮窗后，悬浮窗会与顶部有距离，系统悬浮窗则会到顶部，没有设置偏移量

更新到2.3.0即可，增加了 setEnableSafeArea(false) 即可全屏拖动
