### ISSUE TITLE
使用setSaveDirectionImpl来保存位置不会触发 update 方法

### ISSUE THREAD

**Issue by mtjo** [Petterpx/FloatingX#184]
**你的Fx版本是多少**
2.2.6
```
implementation("io.github.petterpx:floatingx:2.2.6")
implementation("io.github.petterpx:floatingx-compose:2.2.6"
```

**遇到了什么问题**
使用setSaveDirectionImpl来保存位置不会触发 update 方法，确认一下是不是 BUG

**可复现的示例代码 或者 复现步骤**

我代码是这样写的
```

setSaveDirectionImpl(object : IFxConfigStorage {
                override fun clear() {
                    scope.launch {
                        MusicSettingsRepository.floatingPlayerX.set(0f)
                        MusicSettingsRepository.floatingPlayerY.set(0f)
                    }
                }

                override fun getX(): Float {
                   val x=  MusicSettingsRepository.dataStore.getData("floatingPlayerX", 0f)

                    Log.i(TAG, "getX: $x")
                    return  x
                }

                override fun getY(): Float {
                    var y = MusicSettingsRepository.dataStore.getData("floatingPlayerY", 0f)
                    Log.i(TAG, "getY: $y")
                    return y
                }

                override fun hasConfig(): Boolean {
                    return true
                }

                override fun update(x: Float, y: Float) {
                    Log.i(TAG, "update: x:$x y:$y")
                    scope.launch {

                        MusicSettingsRepository.floatingPlayerX.set(x)
                        MusicSettingsRepository.floatingPlayerY.set(y)
                    }
                }

            })

```

### 上面代码日志跟踪，只会在初始化时调用 getX 和getY 来获取位置，位置变更不会触发update来保存新的位置，按我的理解位置变更应该是会触发update 的，我感觉这应该是个 BUG

1.现在临时在onDragIng里手动调用 update方法来解决
2.现在 getx，gety 是能还获取 到数据，但是悬浮窗并没有移动到对应的位置,以下是日志输出

```
2024-11-23 22:39:34.398 10076-10076 MusicService                             I  getX: 1440.0
2024-11-23 22:39:34.401 10076-10076 MusicService                              I  getY: 900.0
```

现在的解决办是自己在另外调用,我感觉这也是个 BUG

```
          setX(x)
           setY(y)
```

**Comment by Petterpx** [comment]
> **你的Fx版本是多少** 2.2.6
> 
> ```
> implementation("io.github.petterpx:floatingx:2.2.6")
> implementation("io.github.petterpx:floatingx-compose:2.2.6"
> ```
> 
> **遇到了什么问题** 使用setSaveDirectionImpl来保存位置不会触发 update 方法，确认一下是不是 BUG
> 
> **可复现的示例代码 或者 复现步骤**
> 
> 我代码是这样写的
> 
> ```
> 
> setSaveDirectionImpl(object : IFxConfigStorage {
>                 override fun clear() {
>                     scope.launch {
>                         MusicSettingsRepository.floatingPlayerX.set(0f)
>                         MusicSettingsRepository.floatingPlayerY.set(0f)
>                     }
>                 }
> 
>                 override fun getX(): Float {
>                    val x=  MusicSettingsRepository.dataStore.getData("floatingPlayerX", 0f)
> 
>                     Log.i(TAG, "getX: $x")
>                     return  x
>                 }
> 
>                 override fun getY(): Float {
>                     var y = MusicSettingsRepository.dataStore.getData("floatingPlayerY", 0f)
>                     Log.i(TAG, "getY: $y")
>                     return y
>                 }
> 
>                 override fun hasConfig(): Boolean {
>                     return true
>                 }
> 
>                 override fun update(x: Float, y: Float) {
>                     Log.i(TAG, "update: x:$x y:$y")
>                     scope.launch {
> 
>                         MusicSettingsRepository.floatingPlayerX.set(x)
>                         MusicSettingsRepository.floatingPlayerY.set(y)
>                     }
>                 }
> 
>             })
> ```
> 
> ### 上面代码日志跟踪，只会在初始化时调用 getX 和getY 来获取位置，位置变更不会触发update来保存新的位置，按我的理解位置变更应该是会触发update 的，我感觉这应该是个 BUG
> 1.现在临时在onDragIng里手动调用 update方法来解决 2.现在 getx，gety 是能还获取 到数据，但是悬浮窗并没有移动到对应的位置,以下是日志输出
> 
> ```
> 2024-11-23 22:39:34.398 10076-10076 MusicService                             I  getX: 1440.0
> 2024-11-23 22:39:34.401 10076-10076 MusicService                              I  getY: 900.0
> ```
> 
> 现在的解决办是自己在另外调用,我感觉这也是个 BUG
> 
> ```
>           setX(x)
>            setY(y)
> ```

OK，今天晚些时候修复

**Comment by Petterpx** [comment]
没复现，可以附带一个可以复现的例子吗 @mtjo

**Comment by mtjo** [comment]
> 没复现，可以附带一个可以复现的例子吗 @mtjo

上面提供的代码有触发 update 吗？我用上面的代码是必现的，只触发 getx,gety,update 不会触发,我代码是 jetpack compose 项目，会不会和这个有关？


###另外现在 getx，gety 是能还获取 到数据，但是悬浮窗并没有移动到对应的位置的原因我找到了，这个是因为composeui 里的页面重载前大小为0导致的,你可以看下面代码的区别
```
//这段代码位置就可以正常初始化
            setLayoutView(
                ComposeView(mContext).apply {
                    setContent {
                        val enable by MusicSettingsRepository.enableFloatingPlayer.asLiveData()
                            .observeAsState(false)
                        val transparency by MusicSettingsRepository.floatingPlayerBackgroundTransparency.asLiveData()
                            .observeAsState(0f)
                        val color by MusicSettingsRepository.floatingPlayerTextColor.asLiveData()
                            .observeAsState()
                        val backgroundColor by MusicSettingsRepository.floatingPlayerBackgroundColor.asLiveData()
                            .observeAsState()

                        val alpha = transparency!!.toFloat() / 100f
                        Box(
                            modifier = Modifier
                                .height(120.dp)
                                .width(320.dp)
                        ) {
                            if (enable!!) { 
                                Card(
                                    colors = CardDefaults.cardColors(
                                        containerColor = Color(backgroundColor!!.toLong(16)).copy(
                                            alpha
                                        ),// 设置背景为透明
                                        contentColor = Color(color!!.toLong(16))
                                    ),
                                    modifier = Modifier
                                        .height(120.dp)
                                        .width(320.dp)
                                ) {
                                    SmallMusicPlayerScreen()
                                }
                            }
                        }
                    }
                }
            )

```

```
//这段代码位置就不初始化 
//注意看这enable 的位置区别
            setLayoutView(
                ComposeView(mContext).apply {
                    setContent {
                        val enable by MusicSettingsRepository.enableFloatingPlayer.asLiveData()
                            .observeAsState(false)
                        val transparency by MusicSettingsRepository.floatingPlayerBackgroundTransparency.asLiveData()
                            .observeAsState(0f)
                        val color by MusicSettingsRepository.floatingPlayerTextColor.asLiveData()
                            .observeAsState()
                        val backgroundColor by MusicSettingsRepository.floatingPlayerBackgroundColor.asLiveData()
                            .observeAsState()

                        val alpha = transparency!!.toFloat() / 100f
   
                        if (enable!!) { 
                            Card(
                                colors = CardDefaults.cardColors(
                                    containerColor = Color(backgroundColor!!.toLong(16)).copy(
                                        alpha
                                    ),// 设置背景为透明
                                    contentColor = Color(color!!.toLong(16))
                                ),
                                modifier = Modifier
                                    .height(120.dp)
                                    .width(320.dp)
                            ) {
                                SmallMusicPlayerScreen()
                            }
                        }
                        
                    }
                }
            )
```

### 已经可以处理位置初始化的问题，但是 update 方法依然不会触发

**Comment by Petterpx** [comment]
> > 没复现，可以附带一个可以复现的例子吗 @mtjo
> 
> 上面提供的代码有触发 update 吗？我用上面的代码是必现的，只触发 getx,gety,update 不会触发,我代码是 jetpack compose 项目，会不会和这个有关？
> 
> ### 另外现在 getx，gety 是能还获取 到数据，但是悬浮窗并没有移动到对应的位置的原因我找到了，这个是因为composeui 里的页面重载前大小为0导致的,你可以看下面代码的区别
> ```
> //这段代码位置就可以正常初始化
>             setLayoutView(
>                 ComposeView(mContext).apply {
>                     setContent {
>                         val enable by MusicSettingsRepository.enableFloatingPlayer.asLiveData()
>                             .observeAsState(false)
>                         val transparency by MusicSettingsRepository.floatingPlayerBackgroundTransparency.asLiveData()
>                             .observeAsState(0f)
>                         val color by MusicSettingsRepository.floatingPlayerTextColor.asLiveData()
>                             .observeAsState()
>                         val backgroundColor by MusicSettingsRepository.floatingPlayerBackgroundColor.asLiveData()
>                             .observeAsState()
> 
>                         val alpha = transparency!!.toFloat() / 100f
>                         Box(
>                             modifier = Modifier
>                                 .height(120.dp)
>                                 .width(320.dp)
>                         ) {
>                             if (enable!!) { 
>                                 Card(
>                                     colors = CardDefaults.cardColors(
>                                         containerColor = Color(backgroundColor!!.toLong(16)).copy(
>                                             alpha
>                                         ),// 设置背景为透明
>                                         contentColor = Color(color!!.toLong(16))
>                                     ),
>                                     modifier = Modifier
>                                         .height(120.dp)
>                                         .width(320.dp)
>                                 ) {
>                                     SmallMusicPlayerScreen()
>                                 }
>                             }
>                         }
>                     }
>                 }
>             )
> ```
> 
> ```
> //这段代码位置就不初始化 
> //注意看这enable 的位置区别
>             setLayoutView(
>                 ComposeView(mContext).apply {
>                     setContent {
>                         val enable by MusicSettingsRepository.enableFloatingPlayer.asLiveData()
>                             .observeAsState(false)
>                         val transparency by MusicSettingsRepository.floatingPlayerBackgroundTransparency.asLiveData()
>                             .observeAsState(0f)
>                         val color by MusicSettingsRepository.floatingPlayerTextColor.asLiveData()
>                             .observeAsState()
>                         val backgroundColor by MusicSettingsRepository.floatingPlayerBackgroundColor.asLiveData()
>                             .observeAsState()
> 
>                         val alpha = transparency!!.toFloat() / 100f
>    
>                         if (enable!!) { 
>                             Card(
>                                 colors = CardDefaults.cardColors(
>                                     containerColor = Color(backgroundColor!!.toLong(16)).copy(
>                                         alpha
>                                     ),// 设置背景为透明
>                                     contentColor = Color(color!!.toLong(16))
>                                 ),
>                                 modifier = Modifier
>                                     .height(120.dp)
>                                     .width(320.dp)
>                             ) {
>                                 SmallMusicPlayerScreen()
>                             }
>                         }
>                         
>                     }
>                 }
>             )
> ```
> 
> ### 已经可以处理位置初始化的问题，但是 update 方法依然不会触发

修复了，更新到2.3.1即可。问题是初始化时浮窗大小没及时更新，导致历史位置设置失败了
