### ISSUE TITLE
系统级悬浮窗 无法继续向下拖拽

### ISSUE THREAD

**Issue by HsiYang506** [Petterpx/FloatingX#188]
**你的Fx版本是多少**
2.3.1
**遇到了什么问题**
系统级悬浮窗 无法继续向下拖拽,疑似parentH - viewH - navigationBarHeight 备注:应用是全屏无状态栏,无导航栏
**可复现的示例代码 或者 复现步骤**
![PixPin_2024-12-10_10-15-57](https://github.com/user-attachments/assets/713582b9-23e9-4dae-b837-ed4366dd0887)
![PixPin_2024-12-10_10-13-39](https://github.com/user-attachments/assets/062490d2-75b7-41e5-9a02-8aeaf6ddd991)
![PixPin_2024-12-10_10-12-58](https://github.com/user-attachments/assets/b78f7da6-004b-4c0b-b064-46d53433c1ab)

https://github.com/user-attachments/assets/275bde4f-96d3-4725-aa80-239ae96dd9a9

**Comment by Petterpx** [comment]
> **你的Fx版本是多少** 2.3.1 **遇到了什么问题** 系统级悬浮窗 无法继续向下拖拽,疑似parentH - viewH - navigationBarHeight 备注:应用是全屏无状态栏,无导航栏 **可复现的示例代码 或者 复现步骤** ![PixPin_2024-12-10_10-15-57](https://private-user-images.githubusercontent.com/19218795/394078523-713582b9-23e9-4dae-b837-ed4366dd0887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDQ2ODYsIm5iZiI6MTczMzg0NDM4NiwicGF0aCI6Ii8xOTIxODc5NS8zOTQwNzg1MjMtNzEzNTgyYjktMjNlOS00ZGFlLWI4MzctZWQ0MzY2ZGQwODg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDE1MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNDQ2OGM1MWY0NTFmOWU5MWIxZWU1N2E2NTZjMjlkZDcyNzdmYWMyOWZiZWQ3NDQzOTkyNzdmOGI3NDQyNGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iQriJ_jhHicmAxEIA1hIPSulIDoLwXbPPf9ZeitVUt4) ![PixPin_2024-12-10_10-13-39](https://private-user-images.githubusercontent.com/19218795/394078594-062490d2-75b7-41e5-9a02-8aeaf6ddd991.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDQ2ODYsIm5iZiI6MTczMzg0NDM4NiwicGF0aCI6Ii8xOTIxODc5NS8zOTQwNzg1OTQtMDYyNDkwZDItNzViNy00MWU1LTlhMDItOGFlYWY2ZGRkOTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDE1MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxYWRiNDQxYTRlNjQ3ODhkZjJhODljYzRhMmM1NWFmNTg0MzY0MTMxOWYyNzRmMTMyN2FkNzUwNzUxZWRlOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QcT48odMIAE1K_ZaaPI-g2dxLNqrsFHWb7ECbC6j1qk) ![PixPin_2024-12-10_10-12-58](https://private-user-images.githubusercontent.com/19218795/394078659-b78f7da6-004b-4c0b-b064-46d53433c1ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4NDQ2ODYsIm5iZiI6MTczMzg0NDM4NiwicGF0aCI6Ii8xOTIxODc5NS8zOTQwNzg2NTktYjc4ZjdkYTYtMDA0Yi00YzBiLWIwNjQtNDZkNTM0MzNjMWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEwVDE1MjYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZTkwNmUyNmY1MmEzM2FiMzQzMDI0OWZkZDM1NjAyZjk3ZjQwZmM0YzlkODM1Nzg1NzlkZGJlMWFmNGJiZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IEXpoZO2SB1QeE1mm9nV7kQraIDywdTIyU-e1dtrxZQ)
> 
>  Screen_recording_20241210_101142.mp4

晚点我加一个Api解决你的问题

**Comment by Petterpx** [comment]
默认现在对于系统浮窗是禁止移动到导航栏与状态栏，故存在了此问题

**Comment by Petterpx** [comment]
已处理，如果要将浮窗展示到状态栏或者导航栏之上，还可以在构建AppHelper时 设置 setEnableSafeArea(false) 即可
