### ISSUE TITLE
点击事件无法正常工作 

### ISSUE THREAD

**Issue by sakura2333** [Petterpx/FloatingX#191]
**你的Fx版本是多少**
2.3.2
**遇到了什么问题**

        FloatingX.install {
            setContext(context = applicationContext)
            setOnClickListener( clickListener =  object : View.OnClickListener {
            override fun onClick(p0: View?) {
                Toast.makeText(applicationContext, "Floating window clicked!", Toast.LENGTH_SHORT).show()
            }
        })
            setScopeType(FxScopeType.SYSTEM_AUTO)
            setLayout(R.layout.floating)  // 设置悬浮窗布局
        }.show()  // 显示悬浮窗

点击事件点几十次才有可能触发一次  很奇怪

     // 给浮窗设置点击事件
        floatingView.findViewById<TextView>(R.id.floating_button).setOnClickListener {
            Toast.makeText(this, "Floating window clicked!", Toast.LENGTH_SHORT).show()
        }
一样的layout 自己写view就没问题
**可复现的示例代码 或者 复现步骤**

**Comment by Petterpx** [comment]
FloatingX. setOnClickListener() 内部做了防抖，将time设置为-1或者0即可。建议使用之前看下Api实现或者文档。
<img width="907" alt="image" src="https://github.com/user-attachments/assets/5e3da613-ffdb-4a8e-8dc5-10a635a4bfdf" />
