### ISSUE TITLE
若是需要在悬浮窗播放SVGA，如何保证动画的连续性

### ISSUE THREAD

**Issue by woilsy** [Petterpx/FloatingX#25]
项目中有使用到svga动画，需要在不同页面之前跳转，但又不能影响动画的播放，要保证它的连续性，在不使用悬浮窗的情况，此方案可以支持吗？

**Comment by Petterpx** [comment]
在不使用悬浮窗时，不会影响你的业务代码。

**Comment by Petterpx** [comment]
> 项目有使用到svga动画，需要在不同页面之前跳转，但又不能影响动画播放，要保证它的连续性，在不使用悬浮窗的情况下，这个方案支持吗？

没在不使用悬浮窗时，不会影响你的业务代码；如果说你想实现的是悬浮窗正在进行某个动画，此时切换页面，需要保证动画连续性。这个也是不影响，因为对于App级悬浮窗而言，view是单例持有，因为view不会销毁，所以动画其实依然在进行，不过在页面切换时没有插入到相应的activity里展示，页面切换完成后，会及时插入，此时如果悬浮窗动画没结束，依然能看到过程，这个过程因为很快，所以并不突兀。

**Comment by woilsy** [comment]
确实是可以的，虽然还会有一点闪烁的感觉。

**Comment by Petterpx** [comment]
> 确实是可以的，同时会有一点发光的感觉。

闪烁这个无法避免，这是因为插入时机是onResume,采用的是监听activity生命周期，所以会有这种情况。
