### ISSUE TITLE
AndroidStudio4.1.3 编译问题

### ISSUE THREAD

**Issue by lin0603** [Petterpx/FloatingX#30]
大佬好,请问我用了AndroidStudio4.1.3开启最新的专案..会出这错误 请问能如何处理呢?谢谢
![image](https://user-images.githubusercontent.com/13999443/140751434-9054e844-7230-4a4f-bd8e-21017fa78597.png)
另外我按了 Use JDK from project structure 后,会跳出这错误
 This version of the Android Support plugin for IntelliJ IDEA (or Android Studio) cannot open this project, please retry with version 2020.3.1 or newer.
再拜托您帮忙小弟解答下,谢谢

**Comment by Petterpx** [comment]
你是直接clone的FloatingX去运行吗，如果是这样的话，建议你删除 .idea下的gradle.xml文件，然后再重新sync一下。

**Comment by Petterpx** [comment]
如果不行的话，你可以尝试删除整个 .idea文件夹，再尝试重新sync.

**Comment by Petterpx** [comment]
sync没有的话，点击下图File->下图位置重启即可尝试：
![image](https://user-images.githubusercontent.com/41142188/140855004-d94df125-d2d9-4330-a1b7-5430a28c8403.png)

**Comment by Petterpx** [comment]
你可以直接拉最新的代码即可，我已经将多余的文件忽略掉了。但是因为我这边gradle的配置是7.x的配置，所以你那边可能仍然需要升级到最新的Android Studio Fox才可以。

**Comment by lin0603** [comment]
谢谢大佬回复.我升级到最新的Android Studio Fox并再将整个专案clone下来.照了以上的步奏做了.现在已经可以正常的执行了.真的非常谢谢您帮忙.

**Comment by Petterpx** [comment]
没事，这个issue就暂时先关闭了，如果有其他问题，请再联系。
