### ISSUE TITLE
新建的专案 无法显示浮窗

### ISSUE THREAD

**Issue by lin0603** [Petterpx/FloatingX#31]
P大,想请教您 这是我自行[新建的专案](url),我是使用java来init跟show.但按了我的showFloat Button半天...都不会显示出来浮窗.请问还有什么设置需注意的呢?
![2021-11-09 202909](https://user-images.githubusercontent.com/13999443/140926938-901cc8e2-9269-4746-baab-085d99537b3c.jpg)

**Comment by Petterpx** [comment]
![image](https://user-images.githubusercontent.com/41142188/140931885-43b7402d-affe-4c37-b100-d243013bc5cc.png)

AppHelper推荐在Application中配置初始化，并且如果初始化时未调用show()，悬浮窗是没办法做到插入到全局的，请参照 demo中的 CustomJavaApplication

**Comment by Petterpx** [comment]
另外，刚才更新了rc-10,show()方法里现在默认会监听全局生命周期。 不过依然建议调用时传递activity, 否则请确保在此前已经调用过show方法。
implementation 'com.github.Petterpx:FloatingX:1.0-rc10'

**Comment by Petterpx** [comment]
这里的设计其实不是特别合理，后面还会再优化一下。

**Comment by lin0603** [comment]
谢谢P大,我马上再依您的建议试试看.

**Comment by Petterpx** [comment]
这个issue暂时先关闭了，如果有其他问题，请再联系😄
