### ISSUE TITLE
增加不想显示的界面

### ISSUE THREAD

**Issue by xiaoxing1992** [Petterpx/FloatingX#32]
现在是支持所有显示的 和  固定想要显示的   可否增加一个 不想显示某几个页面的api

**Comment by Petterpx** [comment]
可以，稍后更新

**Comment by xiaoxing1992** [comment]
> 可以，稍后更新

感谢   我的想法是  默认是添加所有的activity  然后  用黑名单去过滤不想显示的

**Comment by Petterpx** [comment]
> > 可以，稍后更新
> 
> 感谢我的想法是默认显示是添加所有的活动然后用黑名单去过滤的

这样也可以，但是还是需要保留之前的设计，大家自行决定如何去构造

**Comment by xiaoxing1992** [comment]
> > > 可以，稍后更新
> > 
> > 
> > 感谢我的想法是默认显示是添加所有的活动然后用黑名单去过滤的
> 
> 这样也可以，但是还是需要保留之前的设计，大家自行决定如何去构造

是的  这样的话   就需要增加新的api方法开启这个功能 还得在增加一个添加不显示的api

**Comment by Petterpx** [comment]
你好，请更新到rc-11即可。在原有设置全局显示activity后面增加了可变参数，默认为空数组，可以传递不想显示的列表即可。
![image](https://user-images.githubusercontent.com/41142188/141299062-d097d59a-d348-4b1b-9f05-645cc089171b.png)

implementation 'com.github.Petterpx:FloatingX:1.0-rc11'

**Comment by Petterpx** [comment]
具体实现上，相比之前也做了小优化，具体可查看改动代码。
也是感谢你的建议👍

**Comment by xiaoxing1992** [comment]
> 具体实现上，相比之前也做了小优化，具体可查看改动代码。 也是感谢你的建议👍
嗯  很感谢您   方便的话 加我微信  我还有一些小难点 需要向您求助  vx：429487719

**Comment by Petterpx** [comment]
好的，这个issue就先关闭了

**Comment by xiaoxing1992** [comment]
> 好的，这个issue就先关闭了
好的
