### ISSUE TITLE
provider 冲突问题

### ISSUE THREAD

**Issue by harry-jiang** [Petterpx/FloatingX#34]
<provider
            android:name=".impl.lifecycle.FxLifecycleProvider"
            android:authorities="com.petterp.floatingx.impl.lifecycle.fxlifecycleprovider"
            android:exported="false" />

建议改成 android:authorities="${applicationId}.impl.lifecycle.fxlifecycleprovider"
不然整个手机就只能装一个应用了

**Comment by Petterpx** [comment]
感谢反馈,已修正
