### ISSUE TITLE
Class 'com.petterp.floatingx.FloatingX' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.

### ISSUE THREAD

**Issue by venshine** [Petterpx/FloatingX#35]
RT

**Comment by Petterpx** [comment]
升级你的kotlin版本为1.5.21

**Comment by Petterpx** [comment]
> RT

你好，解决了吗，如果解决了，这个issues就暂时先关闭了。有其他问题也欢迎再问

**Comment by venshine** [comment]
> 

建议让宿主引入kotlin可选版本，而不是必须选择1.5.21

**Comment by venshine** [comment]
> 升级你的kotlin版本为1.5.21

建议让宿主引入kotlin可选版本，而不是必须选择1.5.21

**Comment by Petterpx** [comment]
kotlin版本最低1.5.21或以上都行。不是非必须选择

**Comment by Petterpx** [comment]
因为FloatingX使用的是1.5.21,你这个报错的原因是现有的kotlin版本太旧导致。如果要做适配，floatingx得降低到1.4.x才行。目前主流的kt版本都是1.5.x,最新版本为1.6.x，所以在文档里，我贴了最新的kotlin地址。新版都是兼容旧版本，所以不存在什么问题。
