### ISSUE TITLE
禁止拖动后便接收不到 IFxScrollListener 的回调了

### ISSUE THREAD

**Issue by likfe** [Petterpx/FloatingX#37]
不确定这是设计的 Feature 还是 Bug。
请问，可以只监听 IFxScrollListener 而同时不允许用户拖动浮窗吗？

**Comment by likfe** [comment]
目前我的方式是，禁用 `setEnableTouch(false)` ，然后重写布局的根 ViewGroup 的 `onTouchEvent()` 事件，自行处理用户的手势了。

**Comment by Petterpx** [comment]
在设计之处，IFxScrollListener 只是用于在浮窗拖动时的回调，当用户禁用了浮窗移动后，这个接口自然不会收到回调，您要做的应该是监听浮窗内的手势，而浮窗本身是不需要移动的。
为了做到浮窗移动，事件是完全被浮窗拿走了，所以在设计时没有考虑浮窗禁用时内部触摸事件的反馈。
这的确是设计上缺陷，本应该提供一个出口，可以自行处理事件，周末我会出一个api解决这个问题。

**Comment by Petterpx** [comment]
当然如果您有更好的方式也可以fork进行更改，非常欢迎一起维护这个库。
PS：最近因为拔牙缝线的身体原因，一直没能及时看到issues,回复略迟，不好意思

**Comment by Petterpx** [comment]
试试rc14,IFxScrollListener新增了eventIng(MotionEvent)用于接收当前浮窗所有事件，修改dragIng()方法，增加了MotionEvent参数。appcompat降级到了1.2，无需手动引入kt和appcompat，修改了依赖方式。

**Comment by Petterpx** [comment]
![image](https://user-images.githubusercontent.com/41142188/144697771-2e3a40f4-12b1-4342-9195-8cf03d1a0a0e.png)
