### ISSUE TITLE
全局浮层设置回调监听是否存在内存泄漏？

### ISSUE THREAD

**Issue by hanchanpo13** [Petterpx/FloatingX#38]
在activity fragment 等生命周期组件里，设置全局浮层设置回调监听是否存在内存泄漏？

**Comment by Petterpx** [comment]
存在，建议在application中初始化

**Comment by Petterpx** [comment]
> 在activity fragment 等生命周期组件里，设置全局浮层设置回调监听是否存在内存泄漏？
存在，建议在application中初始化。
如果使用的是局部浮窗则不存在此问题，在view被移除或者activity关闭时，浮窗将自动关闭。

**Comment by Petterpx** [comment]
> 在activity fragment 等生命周期组件里，设置全局浮层设置回调监听是否存在内存泄漏？

存在，建议在application中初始化。
如果使用的是局部浮窗则不存在此问题，在view被移除或者activity关闭时，浮窗将自动关闭。

**Comment by Petterpx** [comment]
> 在activity fragment 等生命周期组件里，设置全局浮层设置回调监听是否存在内存泄漏？
Hi，并不存在内存泄漏问题，因为在设置时调用的是全局静态的控制器，不会出现泄漏问题，区别就是可能存在每次进入这个activity或者fragment都可能会重新设置一次。性能上并无差别，使用问题。建议放到application中监听。

**Comment by Petterpx** [comment]
> 在activity fragment 等生命周期组件里，设置全局浮层设置回调监听是否存在内存泄漏？

Hi，并不存在内存泄漏问题，因为在设置时调用的是全局静态的控制器，不会出现泄漏问题，区别就是可能存在每次进入这个activity或者fragment都可能会重新设置一次。性能上并无差别，使用问题。建议放到application中监听。

**Comment by Petterpx** [comment]
> 在activity fragment 等生命周期组件里，设置全局浮层设置回调监听是否存在内存泄漏？

需要注意的是，请勿在相应的监听方法中去保留当前activity对象或者context,否则将出现内存泄漏。全局浮窗的监听器都是静态的，所以这一点需要特别注意。故建议在application中设置更为合适。相应的在application中，如果需要使用浮窗view,可以直接调用control().getView去获取，以便您的逻辑正常执行。

**Comment by Brook688** [comment]
你好。如果点击全局浮层时需要弹出一个Dialog, 这个Dialog 需要持有当前activity 或者 fragment对象，这种情况怎么处理，希望能解答，谢谢。

**Comment by Petterpx** [comment]
> 你好。如果点击全局浮层时需要弹出一个Dialog, 这个Dialog 需要持有当前activity 或者 fragment对象，这种情况怎么处理，希望能解答，谢谢，因为我现在测试的情况是，在不同的页面，持有的都是show() 时的 Context。

Hi,不好意思现在才看到，我会在下个版本增加一个api以便于对浮窗所依附的activity的获取。

**Comment by Petterpx** [comment]
> 你好。如果点击全局浮层时需要弹出一个Dialog, 这个Dialog 需要持有当前activity 或者 fragment对象，这种情况怎么处理，希望能解答，谢谢，因为我现在测试的情况是，在不同的页面，持有的都是show() 时的 Context。

你好，已调整，App级浮窗新增了 getBindActivity() 方法，以便进行调用。你可以尝试一下 1.0.2版本
