### ISSUE TITLE
悬浮窗可以不设置layoutId，直接设置view吗

### ISSUE THREAD

**Issue by litaomn** [Petterpx/FloatingX#42]
因为做的项目是xposed插件，如要重打包进宿主apk里面，没办法设置layoutId，初始化builder的时候，可不可以直接设置view呢，万分感谢

**Comment by Petterpx** [comment]
> 因为做的项目是xposed插件，如要重打包进宿主apk里面，没办法设置layoutId，初始化builder的时候，可不可以直接设置view呢，万分感谢

可以，晚点增加一个功能。

**Comment by Petterpx** [comment]
> 因为做的项目是xposed插件，如要重打包进宿主apk里面，没办法设置layoutId，初始化builder的时候，可不可以直接设置view呢，万分感谢

你好，请更新版本到1.0.3,已新增以下api,便于直接使用:
- updateManagerView(view)
- updateManagerView(obj:(Context)->View)
通过传递相应的view用于浮窗的视图显示。
需要注意的是，
1. 如果是全局浮窗,则view的context必须是application,局部浮窗则必须非application,如果传递错误，将抛出异常提示。为了便于设置，您可通过后者的方式。借此您将根据当前的浮窗等级获得合适的 context ，最后返回View即可。
2. 如果您之前有设置layoutParams(配置方法中设置过),此layoutparams将只会用于layoutId设置的布局，您通过传递view设置的视图将不会采用此layoutParams,默认情况下，将采用wrap-wrap。对于自定义的view,建议您自行设置layoutparams,或者。
3. layoutid与layoutView的最终取决于最终调用的是谁，后者会将前者重置为默认值。

**Comment by litaomn** [comment]
作者真是我辈楷模，本来不指望能添加此功能，没想到作者速度这么快，再次表示敬意

**Comment by litaomn** [comment]
不知道哪里可以打赏，作者大大请给个打赏的渠道

**Comment by Petterpx** [comment]
> 不知道哪里可以打赏，作者大大请给个打赏的渠道

哈哈，感谢！开源这么久，第一次收到打赏。喝个奶茶就行，ღ( ´･ᴗ･` )比心
![image](https://user-images.githubusercontent.com/41142188/187134089-c8f00dd2-6554-4f6c-a660-e4c9a403cad6.png)

**Comment by litaomn** [comment]
ღ( ´･ᴗ･` )比心

**Comment by Petterpx** [comment]
> 因为做的项目是xposed插件，如要重打包进宿主apk里面，没办法设置layoutId，初始化builder的时候，可不可以直接设置view呢，万分感谢

您好，建议更新到1.0.5,之前的setLayoutView时存在异常,已修复
