### ISSUE TITLE
使用过程中bugly上报视图空指针异常。

### ISSUE THREAD

**Issue by bozaixing** [Petterpx/FloatingX#45]
08-24 17:48:28.381 7140 7140 E AndroidRuntime: java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
--
16008-24 17:48:28.381 7140 7140 E AndroidRuntime: at java.util.Objects.requireNonNull(Objects.java:245)
16108-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.petterp.floatingx.view.FxMagnetView.v(SourceFile:1)
16208-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.petterp.floatingx.view.FxMagnetView.s(SourceFile:1)
16308-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.petterp.floatingx.view.FxMagnetView.b(Unknown Source:0)
16408-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.petterp.floatingx.view.b.run(Unknown Source:4)
16508-24 17:48:28.381 7140 7140 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938)
16608-24 17:48:28.381 7140 7140 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
16708-24 17:48:28.381 7140 7140 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:233)
16808-24 17:48:28.381 7140 7140 E AndroidRuntime: at android.os.Looper.loop(Looper.java:344)
16908-24 17:48:28.381 7140 7140 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8204)
17008-24 17:48:28.381 7140 7140 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
17108-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
17208-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

**Comment by Petterpx** [comment]
> 
排查了一遍，发现了唯一可能的地方，FxManagerView内部有强转ViewGroup的时刻,详见updateSize()，您可以更新到1.0.4解决此问题。 感谢反馈

**Comment by Petterpx** [comment]
> ## 08-24 17:48:28.381 7140 7140 E AndroidRuntime: java.lang.NullPointerException: null cannot be cast to non-null type android.view.ViewGroup
> 16008-24 17:48:28.381 7140 7140 E AndroidRuntime: at java.util.Objects.requireNonNull(Objects.java:245) 16108-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.petterp.floatingx.view.FxMagnetView.v(SourceFile:1) 16208-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.petterp.floatingx.view.FxMagnetView.s(SourceFile:1) 16308-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.petterp.floatingx.view.FxMagnetView.b(Unknown Source:0) 16408-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.petterp.floatingx.view.b.run(Unknown Source:4) 16508-24 17:48:28.381 7140 7140 E AndroidRuntime: at android.os.Handler.handleCallback(Handler.java:938) 16608-24 17:48:28.381 7140 7140 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99) 16708-24 17:48:28.381 7140 7140 E AndroidRuntime: at android.os.Looper.loopOnce(Looper.java:233) 16808-24 17:48:28.381 7140 7140 E AndroidRuntime: at android.os.Looper.loop(Looper.java:344) 16908-24 17:48:28.381 7140 7140 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:8204) 17008-24 17:48:28.381 7140 7140 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method) 17108-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589) 17208-24 17:48:28.381 7140 7140 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)

排查了一遍，发现了唯一可能的地方，FxManagerView内部有强转ViewGroup的时刻,详见updateSize()，您可以更新到1.0.4解决此问题。 感谢反馈
