### ISSUE TITLE
java使用问题请教

### ISSUE THREAD

**Issue by pengjunhong** [Petterpx/FloatingX#46]
FxViewHolder中的getView  这个内联函数 ，在java中 是怎么调用?

**Comment by Petterpx** [comment]
> getView

感谢您的反馈，这里的设计不是很好,目前没法调用。您可以暂时先使用getManagerView()，通过findViewById的方式获取浮窗内部您的子view。
下个版本将针对java互调问题进行修正，同时避免java中调用到某些kotlin方法。

**Comment by Petterpx** [comment]
> FxViewHolder中的getView 这个内联函数 ，在java中 是怎么调用?

感谢您的反馈，这里的设计不是很好,目前没法调用。您可以暂时先使用getManagerView()，通过findViewById的方式获取浮窗内部您的子view。
下个版本(预计周末)将针对java互调问题进行修正，同时避免java中调用到某些kotlin方法。

**Comment by Petterpx** [comment]
> FxViewHolder中的getView 这个内联函数 ，在java中 是怎么调用?

从原理上来说，这里是因为使用了 reified 导致，其是kotlin中用于避免泛型类型擦除，但在转为java代码后, 方法名上 使用了 **// $FF: synthetic method** , 从而导致java代码编译时无法访问。

**Comment by pengjunhong** [comment]
好的！

**Comment by Petterpx** [comment]
> FxViewHolder中的getView 这个内联函数 ，在java中 是怎么调用?

您好，您可以更新到1.0.5,已对相关问题进行修复。

**Comment by pengjunhong** [comment]
好的 已经可以了，感谢！
