### ISSUE TITLE
在安卓11,机型redmi k2o pro上没有任何效果

### ISSUE THREAD

**Issue by gitcfly** [Petterpx/FloatingX#49]
参考主页以下方式创建悬浮窗，在安卓11上没有任何效果，机型 redmi k2o pro ，辛苦支持

AppHelper helper = AppHelper.builder()
        .setLayout(R.layout.item_floating)
	.setLayoutView(view)
	.enableFx()
        .build();
FloatingX.init(helper);

**Comment by Petterpx** [comment]
> 参考主页以下方式创建悬浮窗，在安卓11上没有任何效果，机型 redmi k2o pro ，辛苦支持
> 
> AppHelper helper = AppHelper.builder() .setLayout(R.layout.item_floating) .setLayoutView(view) .enableFx() .build(); FloatingX.init(helper);

先说结论，建议您调用一下FloatingX.control().show();

再说原因：
setLayout与setLayoutView二选一即可，具体使用谁取决于两个方法谁时最后被调用的。
您的代码应该不是在Application中被调用，您可以将上述代码移动到Application-onCreate里，然后根据您的需要选择setLayout 或者 setLayoutView，浮窗将在 init初始化后正常显示。
如果非Application,建议您init初始化后，调用show()方法进行显示。

**Comment by Petterpx** [comment]
> 参考主页以下方式创建悬浮窗，在安卓11上没有任何效果，机型 redmi k2o pro ，辛苦支持
> 
> AppHelper helper = AppHelper.builder() .setLayout(R.layout.item_floating) .setLayoutView(view) .enableFx() .build(); FloatingX.init(helper);

还需要注意的是，因为您使用的是全局悬浮窗，如果要采用 setLayoutView 的方式，您需要保证这是一个application级的View。如果您没有太多需求，建议您使用setLayout的方式,由浮窗框架自行管理。

**Comment by Petterpx** [comment]
> 尝试了以下三种方式： 方式1：在Application中使用，无任何效果，代码如下： public class MyApplication extends Application { @OverRide public void onCreate() { super.onCreate(); AppHelper helper = AppHelper.builder() .setLayout(R.layout.float_layout) .enableFx() .build(); FloatingX.init(helper); FloatingX.control().show(); } } 方式2：在普通activity中使用：无任何效果，代码如下：public class MainActivity extends AppCompatActivity { private ActivityMainBinding binding; TessBaseAPI tessApi; @OverRide protected void onCreate(Bundle savedInstanceState) { super.onCreate(savedInstanceState); binding = ActivityMainBinding.inflate(getLayoutInflater()); setContentView(binding.getRoot()); AppHelper helper = AppHelper.builder() .setLayout(R.layout.float_layout) .enableFx() .build(); FloatingX.init(helper); FloatingX.control().show()； } 方式三：在普通activity中使用，并通过按钮事件触发显示，终于出现了悬浮窗，但是仅仅为局部悬浮窗，应用退至后台运行后悬浮窗消失：public class MainActivity extends AppCompatActivity { private ActivityMainBinding binding; TessBaseAPI tessApi; @OverRide protected void onCreate(Bundle savedInstanceState) { super.onCreate(savedInstanceState); binding = ActivityMainBinding.inflate(getLayoutInflater()); setContentView(binding.getRoot()); binding.showFloat.setOnClickListener(new View.OnClickListener() { @OverRide public void onClick(View view) { AppHelper helper = AppHelper.builder() .setLayout(R.layout.float_layout) .enableFx() .build(); FloatingX.init(helper); FloatingX.control().show(); } });}其中 float_layout.xml 内容如下： <?xml version="1.0" encoding="utf-8"?&gt;<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="wrap_content"&gt; <TextView android:layout_width="match_parent" android:layout_height="wrap_content" android:text="好吧,这是一个悬浮窗" /&gt; </LinearLayout&gt;请问下如何才能展示全局的悬浮窗呢
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Petterpx/FloatingX" ***@***.***&gt;; 发送时间:&nbsp;2022年10月14日(星期五) 下午5:37 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Petterpx/FloatingX] 在安卓11,机型redmi k2o pro上没有任何效果 (Issue #49) 参考主页以下方式创建悬浮窗，在安卓11上没有任何效果，机型 redmi k2o pro ，辛苦支持 AppHelper helper = AppHelper.builder() .setLayout(R.layout.item_floating) .setLayoutView(view) .enableFx() .build(); FloatingX.init(helper); 先说结论，建议您调用一下FloatingX.control().show(); 再说原因： setLayout与setLayoutView二选一即可，具体使用谁取决于两个方法谁时最后被调用的。 您的代码应该不是在Application中被调用，您可以将上述代码移动到Application-onCreate里，然后根据您的需要选择setLayout 或者 setLayoutView，浮窗将在 init初始化后正常显示。 如果非Application,建议您init初始化后，调用show()方法进行显示。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

感谢您的反馈，已经复现了该问题。另外因为这是免权限的悬浮窗，不支持在桌面展示，仅支持App内部。

**Comment by Petterpx** [comment]
> 参考主页以下方式创建悬浮窗，在安卓11上没有任何效果，机型 redmi k2o pro ，辛苦支持
> 
> AppHelper helper = AppHelper.builder() .setLayout(R.layout.item_floating) .setLayoutView(view) .enableFx() .build(); FloatingX.init(helper);

您可以更新到1.0.7,即可修复此问题。推荐在Application中初始化。
