### ISSUE TITLE
怎么实现默认所有activity开启悬浮？ addBlackClass这个太麻烦了，要把所有的activity都写一遍？

### ISSUE THREAD

**Issue by lexluthors** [Petterpx/FloatingX#51]
怎么实现默认所有activity开启悬浮？ addBlackClass这个太麻烦了，要把所有的activity都写一遍？

**Comment by Petterpx** [comment]
> 怎么实现默认所有activity开启悬浮？ addBlackClass这个太麻烦了，要把所有的activity都写一遍？

你好，更新到1.0.7 即可。默认就是允许所有页面显示activity,之前的版本存在bug

**Comment by lexluthors** [comment]
> > 怎么实现默认所有activity开启悬浮？ addBlackClass这个太麻烦了，要把所有的activity都写一遍？
> 
> 你好，更新到1.0.7 即可。默认就是允许所有页面显示,之前的版本存在bug

请问1.0.7是哪个分支呢？

**Comment by lexluthors** [comment]
> > 怎么实现默认所有activity开启悬浮？ addBlackClass这个太麻烦了，要把所有的activity都写一遍？
> 
> 你好，更新到1.0.7 即可。默认就是允许所有页面显示,之前的版本存在bug

master报错了。
![image](https://user-images.githubusercontent.com/17924598/196343172-922f81b0-4d5e-4c71-9219-669c0764b3fa.png)
这个找不到。

**Comment by Petterpx** [comment]
> > > 怎么实现默认所有activity开启悬浮？ addBlackClass这个太麻烦了，要把所有的activity都写一遍？
> > 
> > 
> > 你好，更新到1.0.7 即可。默认就是允许所有页面显示,之前的版本存在bug
> 
> master报错了。 ![image](https://user-images.githubusercontent.com/17924598/196343172-922f81b0-4d5e-4c71-9219-669c0764b3fa.png) 这个找不到。

dependencies {
	  implementation 'com.github.Petterpx:FloatingX:1.0.7'
}

**Comment by Petterpx** [comment]
主分支是main,不是master 😂

**Comment by lexluthors** [comment]
> 

你好，我现在需要使用1.0.7的源码进行依赖，不是远程依赖。但是一直有问题。不知道是哪个分支是正确的？main分支和master分支都是有问题的。请问哪个分支是稳定版呢？

**Comment by Petterpx** [comment]
> > 
> 
> 你好，我现在需要使用1.0.7的源码进行依赖，不是远程依赖。但是一直有问题。不知道是哪个分支是正确的？main分支和master分支都是有问题的。请问哪个分支是稳定版呢？

main分支，master分支已经移除了，你本地pull一下，切换到main即可，master可以删除了
