### ISSUE TITLE
main分支拖动卡死，点击事件无效。可以测试一下，必现！

### ISSUE THREAD

**Issue by lexluthors** [Petterpx/FloatingX#52]
main分支拖动卡死，点击事件无效。可以测试一下，必现！

**Comment by Petterpx** [comment]
> main分支拖动卡死，点击事件无效。可以测试一下，必现！

未发现这个问题，你是怎么使用的呢？
dependencies {
	  implementation 'com.github.Petterpx:FloatingX:1.0.7'
}

**Comment by Petterpx** [comment]
> main分支拖动卡死，点击事件无效。可以测试一下，必现！

你可以直接fork，本地运行demo,暂未发现此问题

**Comment by Petterpx** [comment]
建议你git pull一下，然后切换到main分支，已清除历史冗余分支。默认分支为main
