### ISSUE TITLE
我用1.0.7测试的，设置点击事件确实没有回调！我用源码依赖也是一样的问题。不知道哪里出了问题。

### ISSUE THREAD

**Issue by lexluthors** [Petterpx/FloatingX#53]
我用1.0.7测试的，设置点击事件确实没有回调！我用源码依赖也是一样的问题。不知道哪里出了问题。
![image](https://user-images.githubusercontent.com/17924598/196355732-c070c38d-7cd7-401c-a647-cdea1dd1ca41.png)
我这里打了断点确实没有走。

**Comment by Petterpx** [comment]
> 我用1.0.7测试的，设置点击事件确实没有回调！我用源码依赖也是一样的问题。不知道哪里出了问题。 ![image](https://user-images.githubusercontent.com/17924598/196355732-c070c38d-7cd7-401c-a647-cdea1dd1ca41.png) 我这里打了断点确实没有走。

我这边没有发现这个问题，测试点击是没有问题的。你看看还有其他地方操作浮窗吗？

**Comment by lexluthors** [comment]
> 

你的代码确实有问题的，你可以检查一下。 按照你的demo是没有问题。因为你的demo是new的textview添加进去的。我测试的是用layout添加进去的。
![image](https://user-images.githubusercontent.com/17924598/196379629-3178ba6f-5695-4233-aa4c-0c68d373a22b.png)
如果只使用setLayout是一定有问题的。你可以测试一下。这一定是一个bug。

**Comment by Petterpx** [comment]
> > 
> 
> 你的代码确实有问题的，你可以检查一下。 按照你的demo是没有问题。因为你的demo是new的textview添加进去的。我测试的是用layout添加进去的。 ![image](https://user-images.githubusercontent.com/17924598/196379629-3178ba6f-5695-4233-aa4c-0c68d373a22b.png) 如果只使用setLayout是一定有问题的。你可以测试一下。这一定是一个bug。

本地测试过了，通过setLayout(layoutId) 这种方式没问题。你可以试试 test_click_listener 分支，已经将测试代码加入

**Comment by lexluthors** [comment]
> > > 
> > 
> > 
> > 你的代码确实有问题的，你可以检查一下。 按照你的demo是没有问题。因为你的demo是new的textview添加进去的。我测试的是用layout添加进去的。 ![image](https://user-images.githubusercontent.com/17924598/196379629-3178ba6f-5695-4233-aa4c-0c68d373a22b.png) 如果只使用setLayout是一定有问题的。你可以测试一下。这一定是一个bug。
> 
> 本地测试过了，通过setLayout(layoutId) 这种方式没问题。你可以试试 [test_click_listener](https://github.com/Petterpx/FloatingX/compare/main...test_click_listener) 分支，已经将测试代码加入

这太邪乎了。我用你demo的setLayoutView的方式，new了一个textview加进去就可以点击。只要使用setLayout传入布局id就一定不能点击。不知道咋回事。你本地测试竟然没有问题？ 这个不太科学啊。你不会两个都set了吧，后面一个就覆盖了前面一个了。

**Comment by lexluthors** [comment]
大佬，我找到问题了， 用我的布局试试！ 
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="@android:color/transparent"
    android:gravity="center"
    android:orientation="vertical"
    >
    <Button
        android:text="收起"
        android:textStyle="bold"
        android:textColor="@color/white"
        android:id="@+id/floatBall"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="#ff0000"
        android:textSize="14sp"
        />
</LinearLayout>


你把item_floating.xml换成这个布局。试试。换成你的布局就可以。我用自己的布局就不可以。你这个是有指定布局控件一定是cardview才有点击事件吗？ 我把你的布局放到我的代码里面完全没有问题。 换成自己的点击事件无效。 你可以自己测试一下。

**Comment by lexluthors** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:background="@android:color/transparent"
    android:gravity="center"
    android:orientation="vertical"
    >
    <Button
        android:text="收起"
        android:textStyle="bold"
        android:textColor="@color/white"
        android:id="@+id/floatBall"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="#ff0000"
        android:textSize="14sp"
        />
</LinearLayout>`

这是我的布局， button是无法点击的是吧？

**Comment by lexluthors** [comment]
@Petterpx 大佬，你用我的布局试试。一定复现。

**Comment by Petterpx** [comment]
> <?xml version="1.0" encoding="utf-8"?> <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="wrap_content" android:layout_height="wrap_content" android:background="@android:color/transparent" android:gravity="center" android:orientation="vertical" > <Button android:text="收起" android:textStyle="bold" android:textColor="@color/white" android:id="@+id/floatBall" android:layout_width="wrap_content" android:layout_height="wrap_content" android:background="#ff0000" android:textSize="14sp" /> </LinearLayout>

复现了，正在排查

**Comment by Petterpx** [comment]
> @Petterpx 大佬，你用我的布局试试。一定复现。

复现了，正在排查
