### ISSUE TITLE
单个id的点击事件怎么设置

### ISSUE THREAD

**Issue by csh159** [Petterpx/FloatingX#54]
比如悬浮窗的有一个关闭按钮需要设置点击事件

**Comment by Petterpx** [comment]
> 比如悬浮窗的有一个关闭按钮需要设置点击事件

可以在浮窗显示后，使用以下代码处理：
```kotlin
FloatingX.control().updateView {
                    it.getView<View>(R.id.xx).setOnClickListener {
                        Toast.makeText(it.context, "子view", Toast.LENGTH_SHORT).show()
                    }
                }
```

**Comment by Petterpx** [comment]
> > 比如悬浮窗的有一个关闭按钮需要设置点击事件
> 
> 可以在浮窗显示后，使用以下代码处理：
> 
> ```kotlin
> FloatingX.control().updateView {
>                     it.getView<View>(R.id.xx).setOnClickListener {
>                         Toast.makeText(it.context, "子view", Toast.LENGTH_SHORT).show()
>                     }
>                 }
> ```

不过此方法调用具有时机问题，比如你可能需要在浮窗完全显示时调用才有效，需要再增加逻辑处理，目前可以暂时这样处理。
后续我会增加一个api,从而尽可能在初始化时就可以完成点击事件监听。

**Comment by csh159** [comment]
下个版本可以添加多个悬浮窗的支持么？

**Comment by csh159** [comment]
问一下宽度怎么设置。布局宽度设置了match_parent，但是显示挤在一起了

**Comment by Petterpx** [comment]
> 问一下宽度怎么设置。布局宽度设置了match_parent，但是显示挤在一起了

目前只能设置固定大小或者wrap。match的话暂时只能通过获取浮窗view手动设置。 FloatingX.control().getManagerView() 后进行设置。后续会进行调整

**Comment by Petterpx** [comment]
> 下个版本可以添加多个悬浮窗的支持么？

看精力情况，这个不是现阶段的必须支持，预计会在两个版本后增加。

**Comment by csh159** [comment]
好的，谢谢了

**Comment by Petterpx** [comment]
> 比如悬浮窗的有一个关闭按钮需要设置点击事件

你好，请更新到1.1.0即可。

- 子view的点击事件，可以通过监听view的生命周期 initView()实现;
```
// 初始化
setViewLifecycle(object : IFxViewLifecycle {
    override fun initView(view: View) {
      //这里初始化
    }
})
```
- layoutParams问题，目前可以直接通过 setManagerParams() 实现。

**Comment by csh159** [comment]
新版好像拉不下来

**Comment by Petterpx** [comment]
> 新版好像拉不下来

jitpack的问题，等等周末应该就ok了
