### ISSUE TITLE
黑名单设置有问题吧？addInstallBlackClass添加之后，所有的界面都不显示悬浮窗了。

### ISSUE THREAD

**Issue by lexluthors** [Petterpx/FloatingX#56]
黑名单设置有问题吧？addInstallBlackClass添加之后，所有的界面都不显示悬浮窗了。

**Comment by lexluthors** [comment]
没有提供单独的黑名单设置api。 只能在init中设置吗？ 我在application中init之后，想在其他界面设置黑名单怎么操作？调用哪个api呢？我使用FloatingX.init{ addInstallBlackClass(*c) }  ，发现所有的界面都不显示了！

**Comment by Petterpx** [comment]
> 没有提供单独的黑名单设置api。 只能在init中设置吗？ 我在application中init之后，想在其他界面设置黑名单怎么操作？调用哪个api呢？我使用FloatingX.init{ addInstallBlackClass(*c) } ，发现所有的界面都不显示了！

**检查一下，是否调用了 setEnableAllInstall(false)。**

- 此方法为false时，将禁止所有activity显示浮窗，除非将指定添加通过addInstallWhiteClass()添加到白名单中；
- 此方法为true时(默认)，将插入所有activity中进行显示，如果想禁止相应页面显示，可以通过 addInstallBlackClass() 添加到黑名单。
-

**Comment by Petterpx** [comment]
> 没有提供单独的黑名单设置api。 只能在init中设置吗？ 我在application中init之后，想在其他界面设置黑名单怎么操作？调用哪个api呢？我使用FloatingX.init{ addInstallBlackClass(*c) } ，发现所有的界面都不显示了！

目前不支持动态调整黑名单配置，后续可以考虑增加该功能。
