### ISSUE TITLE
设置右上角 怎么不起作用

### ISSUE THREAD

**Issue by 594238813** [Petterpx/FloatingX#59]
```      
private val fragmentFx by createFx {
        setLayout(R.layout.....)
        .setGravity(FxGravity.RIGHT_OR_TOP)
            .build().toControl(this@HomeFragment)
    }
```

```
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/ll_careModel"
    android:layout_width="40dp"
    android:layout_height="wrap_content"
    android:alpha="0.8"
    android:gravity="center"
    android:orientation="vertical"
    android:paddingTop="10dp"
    android:paddingBottom="10dp">

    <ImageView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:src="@mipmap/icon_cardmodel_heart" />
    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dp"
        android:text=""
        android:gravity="center"
        android:textColor="@color/white"
        android:textSize="16sp"
        />

</LinearLayout>
```

这样写 还是在左上角·

**Comment by Petterpx** [comment]
> ```
> private val fragmentFx by createFx {
>         setLayout(R.layout.....)
>         .setGravity(FxGravity.RIGHT_OR_TOP)
>             .build().toControl(this@HomeFragment)
>     }
> ```
> 
> ```
> <LinearLayout
>     xmlns:android="http://schemas.android.com/apk/res/android"
>     android:id="@+id/ll_careModel"
>     android:layout_width="40dp"
>     android:layout_height="wrap_content"
>     android:alpha="0.8"
>     android:gravity="center"
>     android:orientation="vertical"
>     android:paddingTop="10dp"
>     android:paddingBottom="10dp">
> 
>     <ImageView
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:src="@mipmap/icon_cardmodel_heart" />
>     <TextView
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:layout_marginTop="10dp"
>         android:text=""
>         android:gravity="center"
>         android:textColor="@color/white"
>         android:textSize="16sp"
>         />
> 
> </LinearLayout>
> ```
> 
> 这样写 还是在左上角·
测试了下，没有问题啊，你加下我微信 Petterpx,详细看一下

**Comment by Petterpx** [comment]
> 测试了下，没有问题啊，你加下我微信 Petterpx,详细看一下

测试了下，没有问题啊，你加下我微信 Petterpx,详细看一下

**Comment by Petterpx** [comment]
> ```
> private val fragmentFx by createFx {
>         setLayout(R.layout.....)
>         .setGravity(FxGravity.RIGHT_OR_TOP)
>             .build().toControl(this@HomeFragment)
>     }
> ```
> 
> ```
> <LinearLayout
>     xmlns:android="http://schemas.android.com/apk/res/android"
>     android:id="@+id/ll_careModel"
>     android:layout_width="40dp"
>     android:layout_height="wrap_content"
>     android:alpha="0.8"
>     android:gravity="center"
>     android:orientation="vertical"
>     android:paddingTop="10dp"
>     android:paddingBottom="10dp">
> 
>     <ImageView
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:src="@mipmap/icon_cardmodel_heart" />
>     <TextView
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:layout_marginTop="10dp"
>         android:text=""
>         android:gravity="center"
>         android:textColor="@color/white"
>         android:textSize="16sp"
>         />
> 
> </LinearLayout>
> ```
> 
> 这样写 还是在左上角·

测试了下，没有问题啊，你加下我微信 Petterpx,详细看一下

**Comment by 594238813** [comment]
奇怪  这段代码 放到Activity 里面就靠右边了

**Comment by Petterpx** [comment]
> 奇怪 这段代码 放到Activity 里面就靠右边了

我刚的测试代码也是在Act里，应该是bug。我晚点修一下

**Comment by Petterpx** [comment]
> ```
> private val fragmentFx by createFx {
>         setLayout(R.layout.....)
>         .setGravity(FxGravity.RIGHT_OR_TOP)
>             .build().toControl(this@HomeFragment)
>     }
> ```
> 
> ```
> <LinearLayout
>     xmlns:android="http://schemas.android.com/apk/res/android"
>     android:id="@+id/ll_careModel"
>     android:layout_width="40dp"
>     android:layout_height="wrap_content"
>     android:alpha="0.8"
>     android:gravity="center"
>     android:orientation="vertical"
>     android:paddingTop="10dp"
>     android:paddingBottom="10dp">
> 
>     <ImageView
>         android:layout_width="wrap_content"
>         android:layout_height="wrap_content"
>         android:src="@mipmap/icon_cardmodel_heart" />
>     <TextView
>         android:layout_width="match_parent"
>         android:layout_height="wrap_content"
>         android:layout_marginTop="10dp"
>         android:text=""
>         android:gravity="center"
>         android:textColor="@color/white"
>         android:textSize="16sp"
>         />
> 
> </LinearLayout>
> ```
> 
> 这样写 还是在左上角·

已经修复了,请升级到1.1.3即可，调整了api的逻辑。
考虑了替换当前容器，从而用新的包装容器实现，但存在问题：
如果容器的parent为null,即当前容器为顶层容器，常见Fragment中。故现在必须传递FrameLayout为装载容器。
