### ISSUE TITLE
hide方法无效！

### ISSUE THREAD

**Issue by lexluthors** [Petterpx/FloatingX#63]
调用hide方法隐藏悬浮窗， 点击跳转到新的activity又显示出来了。请问怎么回事？ 这个hide方法的有效期或者生命周期是怎么样的？

**Comment by lexluthors** [comment]
理论上不应该是整个app的生命周期都应该隐藏吗？为什么只对当前activity有效？

**Comment by Petterpx** [comment]
感谢你的反馈，这应该是个bug，我这边处理一下。 @lexluthors

**Comment by Petterpx** [comment]
> 调用hide方法隐藏悬浮窗， 点击跳转到新的activity又显示出来了。请问怎么回事？ 这个hide方法的有效期或者生命周期是怎么样的？

试试1.1.5，已修复。
