### ISSUE TITLE
app启动的时候调用hide方法无效。手动点击按钮设置hide却有效！

### ISSUE THREAD

**Issue by lexluthors** [Petterpx/FloatingX#64]
app启动的时候调用hide方法无效。手动点击按钮设置hide却有效！搞不懂这是什么操作！真的怪。只能手动触发hide？

**Comment by Petterpx** [comment]
> app启动的时候调用hide方法无效。手动点击按钮设置hide却有效！搞不懂这是什么操作！真的怪。只能手动触发hide？

感谢你的反馈，这应该是个bug，我这边处理一下。

**Comment by Petterpx** [comment]
> app启动的时候调用hide方法无效。手动点击按钮设置hide却有效！搞不懂这是什么操作！真的怪。只能手动触发hide？

试试1.1.5，已修复。
