### ISSUE TITLE
多次显示隐藏会bug

### ISSUE THREAD

**Issue by crazyzjw** [Petterpx/FloatingX#65]
```
Process: com.jz.jxz, PID: 31958
    java.lang.IllegalStateException: initFxView -> Error,check your layoutId or layoutView.
        at com.petterp.floatingx.view.FxManagerView.initView(FxManagerView.kt:63)
        at com.petterp.floatingx.view.FxManagerView.init(FxManagerView.kt:57)
        at com.petterp.floatingx.impl.control.FxBasisControlImpl.initManager(FxBasisControlImpl.kt:210)
        at com.petterp.floatingx.impl.control.FxBasisControlImpl.initManagerView(FxBasisControlImpl.kt:206)
        at com.petterp.floatingx.impl.control.FxScopeControl.show(FxScopeControl.kt:22)
```

**Comment by crazyzjw** [comment]
> 

<img width="693" alt="image" src="https://user-images.githubusercontent.com/12543049/211282789-379fd07d-cd20-4178-a73e-3bcbb29a646f.png">
是的show() 和 hide() 
我是在create初始化的,来回切换页面就偶现了

**Comment by Petterpx** [comment]
> > 
> 
> <img alt="image" width="693" src="https://user-images.githubusercontent.com/12543049/211282789-379fd07d-cd20-4178-a73e-3bcbb29a646f.png">
> 
> 是的show() 和 hide() 我是在create初始化的,来回切换页面就偶现了

你好，如图是局部浮窗，你能大概描述一下场景吗，以供我这边排错？
- 应用作用域是 Activity中 还是 Fragment?
- show() 及 hide() 是什么情况下被调用？(某个生命周期触发时还是由逻辑触发)

你使用的是自定义view方式，猜测是框架内部弱引用持有ImageView导致被回收，从而触发的初始化异常，我这边写了一个修复版本，你可以以aar方式引入试试。

[floatingx-release.aar.zip](https://github.com/Petterpx/FloatingX/files/10375243/floatingx-release.aar.zip)

**Comment by crazyzjw** [comment]
> > > 
> > 
> > 
> > <img alt="image" width="693" src="https://user-images.githubusercontent.com/12543049/211282789-379fd07d-cd20-4178-a73e-3bcbb29a646f.png">
> > 是的show() 和 hide() 我是在create初始化的,来回切换页面就偶现了
> 
> 你好，如图是局部浮窗，你能大概描述一下场景吗，以供我这边排错？
> 
> * 应用作用域是 Activity中 还是 Fragment?
> * show() 及 hide() 是什么情况下被调用？(某个生命周期触发时还是由逻辑触发)
> 
> 你使用的是自定义view方式，猜测是框架内部弱引用持有ImageView导致被回收，从而触发的初始化异常。 我这边写了一个修复版本，你可以以aar方式引入试试，应该不会有问题了。:)
> 
> [floatingx-release.aar.zip](https://github.com/Petterpx/FloatingX/files/10375243/floatingx-release.aar.zip)
> 
> ps: 如果问题解决了，记得反馈一下哦！✌️
Activity中的
show() 及 hide() 接口返回显示与否 ,先在create初始化,onresume刷新接口,偶现反复进入页面大概率出现的

**Comment by Petterpx** [comment]
> > > > 
> > > 
> > > 
> > > <img alt="image" width="693" src="https://user-images.githubusercontent.com/12543049/211282789-379fd07d-cd20-4178-a73e-3bcbb29a646f.png">
> > > 是的show() 和 hide() 我是在create初始化的,来回切换页面就偶现了
> > 
> > 
> > 你好，如图是局部浮窗，你能大概描述一下场景吗，以供我这边排错？
> > 
> > * 应用作用域是 Activity中 还是 Fragment?
> > * show() 及 hide() 是什么情况下被调用？(某个生命周期触发时还是由逻辑触发)
> > 
> > 你使用的是自定义view方式，猜测是框架内部弱引用持有ImageView导致被回收，从而触发的初始化异常。 我这边写了一个修复版本，你可以以aar方式引入试试，应该不会有问题了。:)
> > [floatingx-release.aar.zip](https://github.com/Petterpx/FloatingX/files/10375243/floatingx-release.aar.zip)
> > ps: 如果问题解决了，记得反馈一下哦！✌️
> > Activity中的
> > show() 及 hide() 接口返回显示与否 ,先在create初始化,onresume刷新接口,偶现反复进入页面大概率出现的

可以试试我发的aar，应该没问题了。

**Comment by crazyzjw** [comment]
> > > > > 
> > > > 
> > > > 
> > > > <img alt="image" width="693" src="https://user-images.githubusercontent.com/12543049/211282789-379fd07d-cd20-4178-a73e-3bcbb29a646f.png">
> > > > 是的show() 和 hide() 我是在create初始化的,来回切换页面就偶现了
> > > 
> > > 
> > > 你好，如图是局部浮窗，你能大概描述一下场景吗，以供我这边排错？
> > > 
> > > * 应用作用域是 Activity中 还是 Fragment?
> > > * show() 及 hide() 是什么情况下被调用？(某个生命周期触发时还是由逻辑触发)
> > > 
> > > 你使用的是自定义view方式，猜测是框架内部弱引用持有ImageView导致被回收，从而触发的初始化异常。 我这边写了一个修复版本，你可以以aar方式引入试试，应该不会有问题了。:)
> > > [floatingx-release.aar.zip](https://github.com/Petterpx/FloatingX/files/10375243/floatingx-release.aar.zip)
> > > ps: 如果问题解决了，记得反馈一下哦！✌️
> > > Activity中的
> > > show() 及 hide() 接口返回显示与否 ,先在create初始化,onresume刷新接口,偶现反复进入页面大概率出现的
> 
> 可以试试我发的aar，应该没问题了。

好的哈,明天回去试试

**Comment by Petterpx** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > <img alt="image" width="693" src="https://user-images.githubusercontent.com/12543049/211282789-379fd07d-cd20-4178-a73e-3bcbb29a646f.png">
> > > > > 是的show() 和 hide() 我是在create初始化的,来回切换页面就偶现了
> > > > 
> > > > 
> > > > 你好，如图是局部浮窗，你能大概描述一下场景吗，以供我这边排错？
> > > > 
> > > > * 应用作用域是 Activity中 还是 Fragment?
> > > > * show() 及 hide() 是什么情况下被调用？(某个生命周期触发时还是由逻辑触发)
> > > > 
> > > > 你使用的是自定义view方式，猜测是框架内部弱引用持有ImageView导致被回收，从而触发的初始化异常。 我这边写了一个修复版本，你可以以aar方式引入试试，应该不会有问题了。:)
> > > > [floatingx-release.aar.zip](https://github.com/Petterpx/FloatingX/files/10375243/floatingx-release.aar.zip)
> > > > ps: 如果问题解决了，记得反馈一下哦！✌️
> > > > Activity中的
> > > > show() 及 hide() 接口返回显示与否 ,先在create初始化,onresume刷新接口,偶现反复进入页面大概率出现的
> > 
> > 
> > 可以试试我发的aar，应该没问题了。
> 
> 好的哈,明天回去试试

快速回复你可以加我微信 Petterpx ，及时响应:)

**Comment by Petterpx** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > <img alt="image" width="693" src="https://user-images.githubusercontent.com/12543049/211282789-379fd07d-cd20-4178-a73e-3bcbb29a646f.png">
> > > > > > 是的show() 和 hide() 我是在create初始化的,来回切换页面就偶现了
> > > > > 
> > > > > 
> > > > > 你好，如图是局部浮窗，你能大概描述一下场景吗，以供我这边排错？
> > > > > 
> > > > > * 应用作用域是 Activity中 还是 Fragment?
> > > > > * show() 及 hide() 是什么情况下被调用？(某个生命周期触发时还是由逻辑触发)
> > > > > 
> > > > > 你使用的是自定义view方式，猜测是框架内部弱引用持有ImageView导致被回收，从而触发的初始化异常。 我这边写了一个修复版本，你可以以aar方式引入试试，应该不会有问题了。:)
> > > > > [floatingx-release.aar.zip](https://github.com/Petterpx/FloatingX/files/10375243/floatingx-release.aar.zip)
> > > > > ps: 如果问题解决了，记得反馈一下哦！✌️
> > > > > Activity中的
> > > > > show() 及 hide() 接口返回显示与否 ,先在create初始化,onresume刷新接口,偶现反复进入页面大概率出现的
> > > 
> > > 
> > > 可以试试我发的aar，应该没问题了。
> > 
> > 
> > 好的哈,明天回去试试
> 
> 快速回复你可以加我微信 Petterpx ，及时响应:)

试试1.1.7，已修复
