### ISSUE TITLE
滑动事件不生效是为什么

### ISSUE THREAD

**Issue by TaiRan666** [Petterpx/FloatingX#67]

**Comment by Petterpx** [comment]
你好，你指的是setScrollListener()的监听器没生效，还是浮窗内部滑动事件不生效？如果是后者，是因为浮窗默认会消费事件，因为需要滑动。如果您内部的view需要事件，你可以在配置浮窗时调用 setEnableTouch(false)，此方法将禁止浮窗拦截事件，事件遵循默认传递流程，相应的，此时浮窗也将无法滑动。

**Comment by TaiRan666** [comment]
对的 我开启了也没有生效 可以滑动 但是事件触发打的日志都没开到 ！ 其实最主要的问题是 它滑一下 就给其他的布局给盖住了
我可以加一下您的微信问问清楚嘛

**Comment by Petterpx** [comment]
> 对的 我开启了也没有生效 可以滑动 但是事件触发打的日志都没开到 ！ 其实最主要的问题是 它滑一下 就给其他的布局给盖住了 我可以加一下您的微信问问清楚嘛

微信：Petterpx
