### ISSUE TITLE
可否动态的实现半隐藏悬浮球效果

### ISSUE THREAD

**Issue by haonan1** [Petterpx/FloatingX#72]
例如，在手指按下的时候，让悬浮窗半隐藏到边缘，然后手指抬起的时候，悬浮窗在恢复到之前的样式

**Comment by Petterpx** [comment]
> 例如，在手指按下的时候，让悬浮窗半隐藏到边缘，然后手指抬起的时候，悬浮窗在恢复到之前的样式

后续会考虑有没有其他方式能快速实现类似功能，Fx提供入口，开发者自定义逻辑，暂时不会增加。
