### ISSUE TITLE
在onresume 里面发生异常 java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by tuzanhua** [Petterpx/FloatingX#80]
android.view.WindowManagerGlobal.findViewLocked (WindowManagerGlobal.java:543)
android.view.WindowManagerGlobal.updateViewLayout (WindowManagerGlobal.java:437)
android.view.WindowManagerImpl.updateViewLayout (WindowManagerImpl.java:101)
android.widget.PopupWindow.update (PopupWindow.java:2221)
android.widget.PopupWindow.update (PopupWindow.java:2342)
android.widget.PopupWindow.alignToAnchor (PopupWindow.java:2512)
android.widget.PopupWindow.access$000 (PopupWindow.java:113)
android.widget.PopupWindow$1.onViewAttachedToWindow (PopupWindow.java:247)
android.view.View.dispatchAttachedToWindow (View.java:19876)
android.view.ViewGroup.dispatchAttachedToWindow (ViewGroup.java:3508)
android.view.ViewGroup.addViewInner (ViewGroup.java:5317)
android.view.ViewGroup.addView (ViewGroup.java:5089)
android.view.ViewGroup.addView (ViewGroup.java:5029)
android.view.ViewGroup.addView (ViewGroup.java:5002)

> com.petterp.floatingx.impl.control.FxAppControlImpl.attach$lib_floatingx_debug (FxAppControlImpl.kt:103)
> com.petterp.floatingx.impl.lifecycle.FxLifecycleCallbackImpl.onActivityResumed (FxLifecycleCallbackImpl.kt:92)

android.app.Application.dispatchActivityResumed (Application.java:453)
android.app.Activity.dispatchActivityResumed (Activity.java:1317)
android.app.Activity.onResume (Activity.java:1856)
androidx.fragment.app.FragmentActivity.onResume (FragmentActivity.java:434)
base.sys.activity.BaseActivity.onResume (BaseActivity.java:196)
com.voiceroom.ui.VoiceRoomActivity.onResume (VoiceRoomActivity.kt:152)

**Comment by Petterpx** [comment]
> findViewLocked

具体的报错日志是什么，看这个堆栈不知道具体是什么报错，还有，是所有onResume里都报错吗，还是只有某个页面。
