### ISSUE TITLE
在application中初始化的问题。

### ISSUE THREAD

**Issue by Staticzll** [Petterpx/FloatingX#81]
启动就奔溃，Caused by: kotlin.UninitializedPropertyAccessException: lateinit property context has not been initialized

**Comment by Staticzll** [comment]
![(N%YZ7FYQ2 J@4S}DZ5740](https://user-images.githubusercontent.com/26913056/224621360-fb0ca837-914f-446f-b6d9-5340ec2ef622.png)
![Y2U%1(ZM7D}V)MML8C3C~S7](https://user-images.githubusercontent.com/26913056/224621514-03dc079a-7b42-4419-86c8-4463d462164e.png)
在activity中调用startService(Intent(this, MyService::class.java))，就出现lateinit property context has not been initialized，麻烦处理一下这个bug。

**Comment by Petterpx** [comment]
> startService(Intent(this, MyService::class.java))

这是多进程原因导致，不过我本地尝试 provider增加multiprocess，并没有生效，可能后续要增加手动设置context。

**Comment by Petterpx** [comment]
> ![(N%YZ7FYQ2 J@4S}DZ5740](https://user-images.githubusercontent.com/26913056/224621360-fb0ca837-914f-446f-b6d9-5340ec2ef622.png) ![Y2U%1(ZM7D}V)MML8C3C~S7](https://user-images.githubusercontent.com/26913056/224621514-03dc079a-7b42-4419-86c8-4463d462164e.png) 在activity中调用startService(Intent(this, MyService::class.java))，就出现lateinit property context has not been initialized，麻烦处理一下这个bug。

可以先在application里判断一下当前进程，非主进程就不要初始化了，后续这里我再想想该怎么优化去支持多进程。

**Comment by Petterpx** [comment]
已更新，1.2.5，初始化浮窗时，需要手动设置setContext()，从而避免该问题。
