### ISSUE TITLE
问一下，怎么动态更新位置？

### ISSUE THREAD

**Issue by csh159** [Petterpx/FloatingX#82]
比如在某些页面距底部30dp,但是有些页面不需要间距？

**Comment by csh159** [comment]
设置setGravity(FxGravity.RIGHT_OR_BOTTOM)，代码调用setBorderMargin(0,0,200,0)无效，会跑到屏幕上面去

**Comment by Petterpx** [comment]
setBorderMargin() 方法是用于设置移动位置的边框，比如setBorderMargin(0,0,200,0)，相当于浮窗可移动位置距离屏幕底部会有200px的偏移量。动态更新位置的话，这个的确之前没考虑过，这边可以增加一个api去处理。

**Comment by Petterpx** [comment]
> 设置setGravity(FxGravity.RIGHT_OR_BOTTOM)，代码调用setBorderMargin(0,0,200,0)无效，会跑到屏幕上面去

setBorderMargin() 方法是用于设置移动位置的边框，比如setBorderMargin(0,0,200,0)，相当于浮窗可移动位置距离屏幕底部会有200px的偏移量。动态更新位置的话，这个的确之前没考虑过，这边可以增加一个api去处理。

**Comment by Petterpx** [comment]
> 比如在某些页面距底部30dp,但是有些页面不需要间距？

新版本1.2.4已增加新的api，moveLocation() 与 moveLocationByVector()，使用示例如图：
<img width="610" alt="image" src="https://user-images.githubusercontent.com/41142188/229349869-444a3257-46a9-470b-8d61-ec9a223e3f92.png">

**Comment by appdev** [comment]
move 有时候不生效

**Comment by appdev** [comment]
必须设置两次才生效

**Comment by appdev** [comment]
> move 有时候不生效

这个是因为先设置了`setGravity`的原因，但是会出现传相同的坐标，悬浮窗还在移动的问题，比如 show的时候传坐标 150，200。后面连续传100,100 会出现在 [150,200] [100,100]来回移动的问题

**Comment by Petterpx** [comment]
> > move 有时候不生效
> 
> 这个是因为先设置了`setGravity`的原因，但是会出现传相同的坐标，悬浮窗还在移动的问题，比如 show的时候传坐标 150，200。后面连续传100,100 会出现在 [150,200] [100,100]来回移动的问题

后续会处理，正在移动时会屏蔽后续的移动坐标。
