### ISSUE TITLE
方案缺陷

### ISSUE THREAD

**Issue by Hynsn** [Petterpx/FloatingX#86]
不知道作者有没有考虑过如何解决：切换 Activity 时悬浮控件短暂消失重绘问题

**Comment by Petterpx** [comment]
> 不知道作者有没有考虑过如何解决：切换 Activity 时悬浮控件短暂消失重绘问题

很好的问题:) ，不过这个问题无法避免，除非考虑使用带权限的浮窗。

对于免权限的，除非是单Activity的应用，否则这个问题一直存在，因为基于Activity的插入，这一点就无法解决。
