### ISSUE TITLE
支持MVVM么

### ISSUE THREAD

**Issue by HeroBarry** [Petterpx/FloatingX#88]
布局内容
![image](https://user-images.githubusercontent.com/7805207/231777074-7d07241d-bd3b-473d-b488-30d0fc34f15b.png)

fragment内使用不了

**Comment by HeroBarry** [comment]
这样可以解决。不知道是否会引发bug


    
![image](https://user-images.githubusercontent.com/7805207/231781356-092da121-3694-4efb-9ff7-4a72fda4a109.png)


![image](https://user-images.githubusercontent.com/7805207/231781524-0bdb7c0d-a36b-4391-80fa-d176d7888a0c.png)

**Comment by Petterpx** [comment]
> 这样可以解决。不知道是否会引发bug
> 
> ![image](https://user-images.githubusercontent.com/7805207/231781356-092da121-3694-4efb-9ff7-4a72fda4a109.png)
> 
> ![image](https://user-images.githubusercontent.com/7805207/231781524-0bdb7c0d-a36b-4391-80fa-d176d7888a0c.png)

噢噢，不会有bug，应该需要考虑浮窗位置，所以浮窗父布局必须是FrameLayout。

**Comment by HeroBarry** [comment]
好的  是一个好库  代码简洁
