### ISSUE TITLE
updateViewContent 不调用show(),悬浮窗也会显示?

### ISSUE THREAD

**Issue by senlinhuahua** [Petterpx/FloatingX#89]
``FloatingX.control().updateViewContent {
                                    Glide.with(Application.CONTEXT)
                                        .load(imagUrl)
                                        .into(it.getView(R.id.iv_floatingx))
                                }``

**Comment by Petterpx** [comment]
> `FloatingX.control().updateViewContent { Glide.with(Application.CONTEXT) .load(imagUrl) .into(it.getView(R.id.iv_floatingx)) }`

updateViewContent不会影响浮窗的显示状态，你可以看一下你的浮窗install()时，是否设置过enableFx(), 如果设置过，那么浮窗是自动插入并显示的。此时你应该看一下你这段代码的调用位置。

**Comment by senlinhuahua** [comment]
额,原来是这样
