### ISSUE TITLE
RTL布局不支持呀，APP重启了之后没效果，华为鸿蒙3.0系统

### ISSUE THREAD

**Issue by hisgod** [Petterpx/FloatingX#90]
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="70dp"
        android:layout_height="70dp">

        <androidx.appcompat.widget.AppCompatImageView
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:src="@drawable/bitmap_main_small_room_bg" />

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/iv_room_logo"
            loadCircleImage="@{bean.roomInfo.avatar}"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:layout_margin="5dp"
            app:layout_constraintBottom_toBottomOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintLeft_toLeftOf="parent"
            app:layout_constraintRight_toRightOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

        <com.opensource.svgaplayer.SVGAImageView
            android:id="@+id/svg"
            android:layout_width="0dp"
            android:layout_height="0dp"
            app:autoPlay="true"
            app:layout_constraintBottom_toBottomOf="@id/iv_room_logo"
            app:layout_constraintEnd_toEndOf="@id/iv_room_logo"
            app:layout_constraintLeft_toLeftOf="@id/iv_room_logo"
            app:layout_constraintRight_toRightOf="@id/iv_room_logo"
            app:layout_constraintStart_toStartOf="@id/iv_room_logo"
            app:layout_constraintTop_toTopOf="@id/iv_room_logo"
            app:source="ic_main_small_room_play.svga" />

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/iv_close_right"
            android:layout_width="8dp"
            android:layout_height="8dp"
            android:layout_marginTop="4dp"
            android:layout_marginEnd="4dp"
            android:src="@drawable/ic_main_small_room_close"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toTopOf="parent" />

    </androidx.constraintlayout.widget.ConstraintLayout>

**Comment by Petterpx** [comment]
> ```
> <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
>     android:layout_width="70dp"
>     android:layout_height="70dp">
> 
>     <androidx.appcompat.widget.AppCompatImageView
>         android:layout_width="match_parent"
>         android:layout_height="match_parent"
>         android:src="@drawable/bitmap_main_small_room_bg" />
> 
>     <androidx.appcompat.widget.AppCompatImageView
>         android:id="@+id/iv_room_logo"
>         loadCircleImage="@{bean.roomInfo.avatar}"
>         android:layout_width="0dp"
>         android:layout_height="0dp"
>         android:layout_margin="5dp"
>         app:layout_constraintBottom_toBottomOf="parent"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintLeft_toLeftOf="parent"
>         app:layout_constraintRight_toRightOf="parent"
>         app:layout_constraintStart_toStartOf="parent"
>         app:layout_constraintTop_toTopOf="parent" />
> 
>     <com.opensource.svgaplayer.SVGAImageView
>         android:id="@+id/svg"
>         android:layout_width="0dp"
>         android:layout_height="0dp"
>         app:autoPlay="true"
>         app:layout_constraintBottom_toBottomOf="@id/iv_room_logo"
>         app:layout_constraintEnd_toEndOf="@id/iv_room_logo"
>         app:layout_constraintLeft_toLeftOf="@id/iv_room_logo"
>         app:layout_constraintRight_toRightOf="@id/iv_room_logo"
>         app:layout_constraintStart_toStartOf="@id/iv_room_logo"
>         app:layout_constraintTop_toTopOf="@id/iv_room_logo"
>         app:source="ic_main_small_room_play.svga" />
> 
>     <androidx.appcompat.widget.AppCompatImageView
>         android:id="@+id/iv_close_right"
>         android:layout_width="8dp"
>         android:layout_height="8dp"
>         android:layout_marginTop="4dp"
>         android:layout_marginEnd="4dp"
>         android:src="@drawable/ic_main_small_room_close"
>         app:layout_constraintEnd_toEndOf="parent"
>         app:layout_constraintTop_toTopOf="parent" />
> 
> </androidx.constraintlayout.widget.ConstraintLayout>
> ```

这块真没研究过，我晚上看看原因:)

**Comment by Petterpx** [comment]
不是布局问题吧，你看看你配置是否正常。
