### ISSUE TITLE
黑名单设置有问题吧。

### ISSUE THREAD

**Issue by lexluthors** [Petterpx/FloatingX#91]
addInstallBlackClass这个为什么不能接收list类型的？ 这个api是非常难用。我还要一个个设置进去吗？ 这个太麻烦了吧。我现在只有一个黑名单list，我没法使用该api传递进去。

**Comment by Petterpx** [comment]
> 

设计之初只是为了方便增加多个，先forEach一下代替吧，下个版本加。

**Comment by Petterpx** [comment]
> addInstallBlackClass这个为什么不能接收list类型的？ 这个api是非常难用。我还要一个个设置进去吗？ 这个太麻烦了吧。我现在只有一个黑名单list，我没法使用该api传递进去。

更新了，1.2.5，新增了同名方法。
