### ISSUE TITLE
横竖屏切换位置会发生变化

### ISSUE THREAD

**Issue by lexluthors** [Petterpx/FloatingX#92]
横竖屏切换位置会发生变化，位置不会复原。请问这个问题是否合并到main分支了呢？

**Comment by Petterpx** [comment]
> 横竖屏切换位置会发生变化，位置不会复原。请问这个问题是否合并到main分支了呢？

#87

**Comment by Petterpx** [comment]
![image](https://user-images.githubusercontent.com/41142188/234790087-8526cc21-62b3-4312-8645-3e2ef9d2ca7b.png)

**Comment by lexluthors** [comment]
@Petterpx 我的意思是我切换横竖屏，并没有改变悬浮的任何位置，我再切到竖屏，理论上应该位置不变才对啊。但是fx会发生变化啊。

**Comment by lexluthors** [comment]
#87 并没有修复这个问题吧。上面给的两个解决方案都是无效的。

**Comment by lexluthors** [comment]
@Petterpx 我觉得可以保存两个位置，一个横屏一个竖屏的，分开保存，这样就可以完美解决。

**Comment by Petterpx** [comment]
> @Petterpx 我觉得可以保存两个位置，一个横屏一个竖屏的，分开保存，这样就可以完美解决。避免了复杂的逻辑计算。

屏幕的比例不止有横竖屏，也存在小窗口时的随意大小拖动，所以逻辑过于冗余，暂时不考虑解决，故只处理边界。之前尝试过处理，但不尽人意。

**Comment by lexluthors** [comment]
@Petterpx  ok
