### ISSUE TITLE
贴边状态下上下滑动会卡顿

### ISSUE THREAD

**Issue by fringesy** [Petterpx/FloatingX#95]
版本：1.2.5
开启边缘吸附 setEnableEdgeAdsorption(true) 后上下滑动会有明显卡顿

**Comment by fringesy** [comment]
发现是跟点击事件有关系，监听了某个 view 的点击事件之后，手指点击对应 view 开始上下滑动时就会出现卡顿

**Comment by Petterpx** [comment]
好的，晚点看看，大概明天。
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年06月25日 15:01 |
| 收件人 | Petterpx/FloatingX ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [Petterpx/FloatingX] 贴边状态下上下滑动会卡顿 (Issue #95) |

版本：1.2.5
开启边缘吸附 setEnableEdgeAdsorption(true) 后上下滑动会有明显卡顿

**Comment by Petterpx** [comment]
> setEnableEdgeAdsorption

目前没发现这个原因，你能写个demo吗？或者发一下你的示例

**Comment by fringesy** [comment]
> > setEnableEdgeAdsorption
> 
> 目前没发现这个原因，你能写个demo吗？或者发一下你的示例 @fringesy

你好，已上传demo，仓库内有模拟器录屏。
https://github.com/fringesy/FloatingXDemo

**Comment by Petterpx** [comment]
> > > setEnableEdgeAdsorption
> > 
> > 
> > 目前没发现这个原因，你能写个demo吗？或者发一下你的示例 @fringesy
> 
> 你好，已上传demo，仓库内有模拟器录屏。 https://github.com/fringesy/FloatingXDemo

pass，浮窗手势拦截 逻辑异常导致。

**Comment by Petterpx** [comment]
试试1.2.6，已修复。
