### ISSUE TITLE
setLayoutView 之后getView为null

### ISSUE THREAD

**Issue by DuZhengLin17** [Petterpx/FloatingX#98]
val view = View.inflate(application,R.layout.floating_game,null)
        FloatingX.install {
            setContext(this@QFMainActivity)
            setLayoutView(view)
        }

val view= FloatingX.control().getView()
view?.findViewById<ImageView>(R.id.fg_view)?.loadImg(it.picture)
FloatingX.control().show(_mActivity)
但是发现view为null

**Comment by Petterpx** [comment]
getView()方法必须在show()之后进行调用，否则会出现view为null问题，主要原因是Fx是基于懒加载的逻辑，只有show()之后，真正的浮窗view才会初始化。
