### ISSUE TITLE
双指触摸崩溃问题

### ISSUE THREAD

**Issue by nedhuo** [Petterpx/FloatingX#99]
版本1.2.6
机型 华为荣耀8x
在多根手指触摸屏幕的情况下 当第一根手指在悬浮窗外，第二根手指触摸悬浮窗的时候 会触发 pointerIndex out of range 异常

**Comment by Petterpx** [comment]
> 版本1.2.6 机型 华为荣耀8x 在多根手指触摸屏幕的情况下 当第一根手指在悬浮窗外，第二根手指触摸悬浮窗的时候 会触发 pointerIndex out of range 异常

使用的是全局浮窗吗，具体的浮窗xml与配置方式能发一下吗？

**Comment by nedhuo** [comment]
不是全局浮窗 是绑定在Fragment上的 
 测了两个华为机型 都是存在的。其他机型没出现该问题 
 
 private val activityFx by createFx {
        setLayout(R.layout.view_home_newer_discount_enter)
        setEnableLog(BuildConfig.DEBUG, "newer_enter")
        setEnableEdgeAdsorption(true)
        setGravity(FxGravity.RIGHT_OR_CENTER)
        setViewLifecycle(object : IFxViewLifecycle {
            override fun initView(view: View) {
                // 在这里您将拿到可靠的内部view,从而初始化事件
                view.run {
                    findViewById<ImageView>(R.id.iv_newerDiscountEnter)?.debounceClick {
                        startActivity(Intent(context, RechargeNewerDiscountActivity::class.java))
                    }

                    findViewById<ImageView>(R.id.iv_closeNewerEnter)?.debounceClick {
                        newerDiscountEnterCloseClick.invoke()
                    }
                }
            }
        })
        setScrollListener(object : IFxScrollListener {
            override fun down() {
                //禁止ViewPager2滑动事件
                LiveEventBus.get<Boolean>(LiveEventConstants.HOME_VIEWPAGE2_INPUT_ENABLE)
                    .post(false)
            }

            override fun dragIng(event: MotionEvent, x: Float, y: Float) {

            }

            override fun eventIng(event: MotionEvent) {

            }

            override fun up() {
                //开启ViewPager2滑动事件
                LiveEventBus.get<Boolean>(LiveEventConstants.HOME_VIEWPAGE2_INPUT_ENABLE)
                    .post(true)
            }
        })

        build().toControl(this@HomeRecommendFragment)
    }

**Comment by nedhuo** [comment]
![image](https://github.com/Petterpx/FloatingX/assets/32531201/e6511971-374a-47f2-b3b9-8cbf4655fb7e)
问题点 在 FxManagerView中的这个位置 
应该是 MotionEvent.getX(touchDownId) touchDownId > 0 引发的

**Comment by Petterpx** [comment]
> ![image](https://user-images.githubusercontent.com/32531201/253485957-e6511971-374a-47f2-b3b9-8cbf4655fb7e.png) 问题点 在 FxManagerView中的这个位置 应该是 MotionEvent.getX(touchDownId) touchDownId > 0 引发的

ok，我晚点排查下，你着急的话可以先加我微信 Petterpx，我晚上解决。

**Comment by Petterpx** [comment]
已修复，1.2.7
